### PR TITLE
UI Improvement of Product Cards in Home Page and Category Section

### PR DESCRIPTION
**Pull request by Abbas7120**
Home Page :
image

Category Section :
image

UI Improvement Done !

### CODE REVIEW

**Comment by mdazfar2** [comment]
Hey @Abbas7120, please resolve your conflict and update your synced fork so that I can merge your PR accordingly.

**Comment by Abbas7120** [comment]
But where is the conflict

**Comment by Abbas7120** [comment]
Is it resolved

**Comment by Abbas7120** [comment]
image
But in my local host no conflict after merging

**Comment by Abbas7120** [comment]
Sir due to my mistake I removed Logo and add new logo from your github readme of Ezyshop so Sir I hope you can easily fixed it name is same ezyshop.png

**Comment by Abbas7120** [comment]
But I resolved my conflict so merge it and please don't  remove my PR for my mistake !

**Comment by mdazfar2** [comment]
@Abbas7120 In the current deployed link, there are a total of 9 categories, but in your PR, only 6 categories are shown, and the logo isn't visible. Please update all of these and let me know. For now, I cannot merge your pull request. Thank you.

**Comment by Abbas7120** [comment]
Ok sir I will do it !

**Comment by Abbas7120** [comment]
Please review again , merge  and assign Label of **Level 3** as I changes logo in all sections where it is not present for making it more good ! I hope you understand ! 

image

**Comment by Abbas7120** [comment]
I just updated it. Please merge it .

**Comment by mdazfar2** [comment]
@Abbas7120 I apologize, but I need to close this pull request for now. Please don't be discouraged! The logo is not visible

**Pull request closed without merging**
