### PR TITLE
Implement Blog Schema and Data Fetching for Blog Functionality

### LINKED ISSUE #928: [Feat] Setup Blog Schema and Implement Blog Data Fetching from Database
### Description
The blog functionality is not yet implemented in the application. To support blog posts, we first need to create a database schema for blogs and set up fetching data from the database. This will provide the foundation for adding blog-related features in future tasks, such as displaying blog summaries and individual blog content on the frontend.

**Proposed Solution:**

1. **Define the Blog Schema:**
   - Create a new `Blog` model in the `schema.prisma` file with fields such as:
     - `id`: Unique identifier for each blog.
     - `title`: Title of the blog post.
     - `content`: Main content of the blog.
     - `image`: URL for the blog's cover image.
     - `authorId`: Identifier linking the blog to a `User`.
     - `createdAt`: Timestamp of when the blog was created.
     - `updatedAt`: Timestamp of when the blog was last updated.
   - Establish relationships if needed (e.g., link blogs to `User` as `author`).
   - Run `prisma db push` to sync the new schema with the MongoDB database.

2. **Create Sample Blog Data:**
   - Add 2-3 initial blog entries to the database to facilitate testing of the fetching logic.

3. **Set Up Data Fetching Logic:**
   - Implement backend API endpoints to retrieve blog data.
   - Create endpoints such as:
     - `GET /api/blogs`: Fetch a list of blog summaries.
     - `GET /api/blogs/:id`: Fetch full details of a specific blog by id.

   - Ensure the data retrieval works correctly and returns the necessary fields for displaying on the frontend.

**Expected Outcome:**
   - A `Blog` schema is defined in the database, and blog data is stored correctly.
   - API endpoints for fetching blog summaries and individual blog details are functional.
   - Initial blog data is available in the database for testing further frontend implementation.

**Additional Information:**  
This foundational setup will allow for a seamless transition to implementing the Blog Grid page and individual Blog Page functionality in a follow-up issue. The next step will focus on dynamically loading the blog content using this database connection.

### Screenshots

Current blog page with static details: 
 
image

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by kavya410004**
## Description

This PR addresses the foundational setup for the blog functionality as described in the issue. The main tasks completed include defining the Blog schema, seeding the database with sample blog entries, setting up API endpoints for fetching blog data, and testing the implementation.

### Changes Made:
1. **Blog Schema Definition**:
   - Added a `Blog` model to the `schema.prisma` file with the following fields:
     - `id`: Unique identifier for each blog (primary key).
     - `title`: Title of the blog post.
     - `content`: Main content of the blog.
     - `image`: URL of the blog's cover image.
     - `author`: Admin is the default author.
     - `createdAt`: Timestamp of when the blog was created.
     - `label`: Label of the blog.
     - `metaDescription`: Short summary of the blog.

2. **Seeding the Database**:
   - Added a script in `seed.ts` to add 3 sample blog posts to the database.
   - This sample data helps in testing the API endpoints and frontend rendering.

3. **Implemented API Endpoints**:
   - Created the following API endpoints for fetching blog data:
     - **GET /api/blogs**: Fetches a list of blog summaries.
     - **GET /api/blogs/:id**: Fetches full details of a specific blog by its ID.
   - These endpoints return the necessary fields for displaying blog summaries and individual blog details on the frontend.

4. **Frontend Integration**:
   - Rendered the fetched blog data on the blogs grid page.
   - Displayed blog summaries using data from the `/api/blogs` endpoint.

5. **Testing**:
   - Verified that `GET /api/blogs` correctly returns a list of blog summaries.
   - Tested `GET /api/blogs/:id` by fetching individual blog details and console logging the specific blog object to ensure data accuracy.
   - Checked that the blogs grid page correctly displays the sample blog posts.

### Expected Outcome:
- The blog data is stored correctly in the database, and the API endpoints fetch the required information.
- The blog summaries are displayed on the blogs grid page.
- The individual blog endpoint returns the full details of a specific blog as expected.

### How to Test:
1. Run `prisma db push` to sync the updated schema.
2. Run the seed script to populate the database with sample blogs.
3. Start the server and navigate to `/api/blogs` to check the list of blogs.
4. Test the endpoint `/api/blogs/:id` by replacing `:id` with a valid blog ID to see the specific blog details.
5. Visit the blogs grid page on the frontend to verify that the blog summaries are displayed.

### Additional Information:
- This PR sets up the groundwork for future blog-related features like the Blog Grid page and individual Blog Page.
- The next step will involve dynamically loading the blog content into the frontend pages.

---

### PR Checklist:
- [x] Added the Blog model to `schema.prisma`.
- [x] Ran `prisma db push` to sync with MongoDB.
- [x] Seeded the database with 3 sample blog posts.
- [x] Implemented API endpoints for fetching blog summaries and individual blog details.
- [x] Verified the functionality through console logs and frontend rendering.

---

Feel free to copy this template, modify it if needed, and use it while raising the pull request! It provides a clear overview of the problem, solution, and testing steps, making it easy for reviewers to understand your changes.

<br/>

## Related Issues

- Closes #928 

<br/>

## Screenshots / videos (if applicable)

**Blogs Page:** The blogs data is fetched from database except the number of comments. It can also be fetched from database after comments schema is implemented.
Screenshot 2024-10-26 084321

**Testing of `api/blog/:id` endpoint:** object printed on console.
Screenshot 2024-10-26 083035

### CODE REVIEW

**Comment by kavya410004** [comment]
@mdazfar2 I have checked it now, I missed the `npm run lint` step. I'll make the changes and let you know.

**Comment by mdazfar2** [comment]
@kavya410004 It still showing error in vercel deployment.



{FE41D8EC-628F-428A-A082-7695DF3AE8F2}

**Comment by kavya410004** [comment]
@mdazfar2 I haven't made the changes yet as I don't have my laptop with me. I'll update it by evening.

**Comment by mdazfar2** [comment]
Okay @kavya410004.

**Comment by kavya410004** [comment]
Hello @mdazfar2 , I have made the changes, could you please review it now?

**Review by mdazfar2 — APPROVED** [review]
Fantastic Work @kavya410004

**Pull request merged**
