### PR TITLE
 Added gap between Trending Deals Cards

### PR DESCRIPTION
**Pull request by ansiace**
This pull request addresses the bug where the **Trending Deals** cards were overlapping and touching the bottom of other cards when hovered. This issue affected the visual hierarchy and led to a cluttered appearance on hover.

#### Problem:
- When hovering over the **Trending Deals** cards, the card edges were touching the bottom of adjacent cards, creating a disorganized layout.
- This bug disrupted the overall user experience and made the UI appear less polished.

image

### CODE REVIEW

**Comment by ansiace** [comment]
- closes #888

**Comment by mdazfar2** [comment]
Hey @ansiace, please sync your fork and let me know once you’ve done it.

**Comment by ansiace** [comment]
done @mdazfar2 please check it.

**Review by mdazfar2 — APPROVED** [review]
lgtm 🎉

**Pull request merged**
