### PR TITLE
Start Shopping Button Now Visible

### LINKED ISSUE #394: `Start Shopping` Button Not Visible
`Start Shopping` Button Is Not Visible:

- use of proper font size and css display feature will make it more visible.
-  ` call to action` for customer will be improved
Screenshot 2024-10-10 104012
@mdazfar2 assign this task to me

### PR DESCRIPTION
**Pull request by Adarsh-Chaubey03**
## Description

- made `start shopping` button visible to customers
- clear `call to action`

<br/>

## Related Issues

- Closes #394 

<br/>

## Screenshots / videos (if applicable)

- Normal View
Screenshot 2024-10-10 111957

- After Hovering it

Screenshot 2024-10-10 112005
@mdazfar2 @Kavita1928 please review this pr

### CODE REVIEW

**Comment by mdazfar2** [comment]
hey @Adarsh-Chaubey03 the hover color is not matching the website UI please do it as matching to the website

**Comment by Adarsh-Chaubey03** [comment]
this is how the button looks now when hovered:
image
DONE @mdazfar2

**Comment by mdazfar2** [comment]
Okay @Adarsh-Chaubey03 update sync fork once and let me know

**Comment by Adarsh-Chaubey03** [comment]
image
updated @mdazfar2

**Pull request closed without merging**
