### PR TITLE
Form Validation completed for "leave a comment" form - ISSUE #45

### PR DESCRIPTION
**Pull request by clownfish1805**
1. Ensured  the "Name" , "Email" and "Comment" fields are not left empty before submission.
2. If empty, error messages are popped.
3. Email validation is done to follow proper format.
4. Character limit for Comment is given around 500 characters.

### CODE REVIEW

**Comment by clownfish1805** [comment]
@mdazfar2 I have resolved the issue. Please check.

**Comment by mdazfar2** [comment]
@clownfish1805, mention the issue using a hashtag (#) so we can understand which issue your PR is referencing, and label your PR accordingly. Thank you!

**Comment by clownfish1805** [comment]
@mdazfar2 The issue is #45.

**Comment by mdazfar2** [comment]
hey @clownfish1805 update sync fork and let me konw

**Comment by clownfish1805** [comment]
@mdazfar2 I have unfortunately closed this pr, also i have created a new one Kindly check it please.

**Pull request closed without merging**
