### PR TITLE
Fix/images in about page 493

### LINKED ISSUE #493: [BUG] Images Not Displaying on the "About Us" Page in Next.js
### Description

The images on the "About Us" page are currently not being displayed in the Next.js version of the project. This issue needs to be addressed to ensure that all images load correctly and are visible to users on the "About Us" page.

**Proposed Solution:**

I would like to take on this issue and work on fixing the image display problem. This would involve:

- Debugging the image import paths or sources.
- Ensuring images are correctly optimized and rendered in the Next.js environment.
- Testing the solution across various devices to ensure consistency.

### Screenshots

image
image

### Any additional information?

_No response_

### What browser are you seeing the problem on?

_No response_

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by kavya410004**
## Description

The problem was caused by an inconsistency between the image file names and their references in the code. Specifically, one of the image files had spaces in its name, but the code referenced the file path without these spaces. This discrepancy prevented the images from being loaded correctly on the "About Us" page.

**Changes made:**

- Corrected the file name to match the path used in the code.
- Updated the references in the Next.js components to ensure proper image linking.
- Verified that the images now load properly on the page and display as expected.

<br/>

## Related Issues

- Closes #493 

<br/>

## Screenshots 

image

### CODE REVIEW

**Comment by kavya410004** [comment]
@mdazfar2 There were conflicts in  main-nav.tsx and stores.tsx, I have also fixed those conflicts and made sure they were responsive as shown in pr #475 . Could you review it? Let me know if further changes are required.

**Comment by mdazfar2** [comment]
@kavya410004 please review it again and update sync fork that every thing is correct or not

**Comment by kavya410004** [comment]
> @kavya410004 please review it again and update sync fork that every thing is correct or not

Done, can you review it now?

**Review by mdazfar2 — APPROVED** [review]
Looks good to me

**Pull request merged**
