### PR TITLE
Fixed issue #313: Links added to Contact Us Page

### PR DESCRIPTION
**Pull request by Arghya-Chakraborty0812**
## Description

Links were added to the Contact us Page

<br/>

## Related Issues

None
- Closes #

<br/>

## Screenshots / videos (if applicable)

Screenshot 2024-10-08 at 3 40 26 PM
Screen Recording to show working links:
[Screen Recording 2024-10-08 at 3.41.00 PM.zip](https://github.com/user-attachments/files/17291727/Screen.Recording.2024-10-08.at.3.41.00.PM.zip)

### CODE REVIEW

**Comment by Arghya-Chakraborty0812** [comment]
Please assign me level 1

**Comment by mdazfar2** [comment]
Hey @Arghya-Chakraborty0812, you created a pull request directly without raising any issue. I hope you are new to open source. I request you to read the [contributing guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md), as they will help you work on open source. Please don't create pull requests directly. Thank you.

**Comment by Arghya-Chakraborty0812** [comment]
This issue was assigned to me, check issue #313 
Screenshot 2024-10-09 at 10 52 15 AM

**Comment by Arghya-Chakraborty0812** [comment]
I had already raised an issue #313 for it and was assigned it , after that I proceeded to create a PR.Pls check it once I have provided screenshots in the comments of the PR as well.

**Comment by mdazfar2** [comment]
Okay @Arghya-Chakraborty0812 will review your PR's soon

**Pull request closed without merging**
