### PR TITLE
'Add to cart' and 'wishlist' pages are added

### PR DESCRIPTION
**Pull request by NIKITABARANWAL890**
Issue no. #538 

**Search bar, Profile, Cart and Wishlist buttons are added.**

https://github.com/user-attachments/assets/fd05633c-0e2b-4add-86f0-c1f9ed380a83

**Add to cart and Wishlist pages were also added alongwith the checkout section.**

https://github.com/user-attachments/assets/43e1a52f-fcc5-463c-bc92-16a4e77df1f0

@mdazfar2 @Kavita1928 i've done the task assigned, can you review it once?

### CODE REVIEW

**Comment by NIKITABARANWAL890** [comment]
@mdazfar2 @Kavita1928 
kindly review the PR

**Review by mdazfar2 — APPROVED** [review]
Looks good to me.

**Comment by mdazfar2** [comment]
Hey @NIKITABARANWAL890, I don't know how that feature got removed from the navbar. Can you resolve it as soon as possible? If you can, please raise an issue and let me know, and create a PR quickly.


When we switch from the home page to the about page or any other page using the navbar, the mark does not show, as you can see in the screen recording below for better understanding.


https://github.com/user-attachments/assets/6931d09a-0953-407b-9e6e-6e0bc48157ce


<br>

_Hope you understand_

**Comment by NIKITABARANWAL890** [comment]
[like]  Nikita Baranwal reacted to your message:
________________________________

**Comment by NIKITABARANWAL890** [comment]
Hello @***@***.***> sir,
I hope this message finds you well.

I just wanted to ask you, why you stopped assigning me the issues and merging the PRs I made, if there was something you didn't like about my work, you could just have guided me once.

And for the part of raising issues multiple times, I kept in mind that also and reduced the number of issues as well and apologizing for the same.

Kindly let me know the reason as it's disturbing me mentally.

Kind regards,

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mdazfar2** [comment]
Hey @NIKITABARANWAL890, just wanted to let you know that we have converted our website to Next.js and Tailwind CSS framework for the backend and payment integration. So, please close all the issues and PRs you raised for the previous HTML and CSS website, as we've now converted all the code. Please don't feel discouraged that Azfar didn't respond earlier; you can see there are over 90 issues and pull requests that I haven't responded to. Right now, I'm reaching out to you directly. Thank you so much for all your contributions.

**Comment by NIKITABARANWAL890** [comment]
Okay sir,
Thankyou so much!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Pull request merged**
