### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by kjl98**
Add some content.

### CODE REVIEW

**Review by thakuratul2 — APPROVED** [review]

**Comment by kjl98** [comment]
"Hey [@mdazfar2 ], I just wanted to extend a massive thank you for merging my changes into your repository. Your project has been incredibly inspiring, and I'm thrilled to have contributed. Looking forward to collaborating more in the future!"

Just something from the heart. Always lands well. 🌟

Regards @kjl98

**Comment by kjl98** [comment]
Sir, can you please add some labels - hacktoberfest-accepted, gssoc-extd

**Comment by Tejashri-Taral** [comment]
@sanjay-kv @MastanSayyad Can you please review this?

**Review by MastanSayyad — COMMENTED** [review]
Level 2 is not applicable @mdazfar2 please change the labels and add me as a collaborator for further monitoring 

image

**Comment by mdazfar2** [comment]
@Tejashri-Taral I'm boosting the confidence of these newbie contributors by giving more GSSOC-ext points to those who truly work on open source first time, but don't worry, I'll reduce their points.

**Comment by mdazfar2** [comment]
> Level 2 is not applicable @mdazfar2 please change the labels and add me as a collaborator for further monitoring 
> 
> image
> 



@MastanSayyad I invited you to collaborate. Please accept.

**Comment by MastanSayyad** [comment]
Hi @mdazfar2 I didn't get any invitation can you send it again

**Pull request merged**
