### PR TITLE
made a shops page with filter

### PR DESCRIPTION
**Pull request by riyarane46**
issue #174 
@mdazfar2 
you had assigned me this issue to make a shops page with filter category

first to see all the shops with no category specification i have linked the shops page with the about us explore stores button . 

https://github.com/user-attachments/assets/b5a1d978-94ce-490e-8edf-46fe87a03ef2

and now for filtered category shops 
i  linked the shops page with the category page shop now button 
so that we can see only those shops of specific category we selected

https://github.com/user-attachments/assets/c20f2260-ca78-42f2-b48f-a8b28e799b7b

each shop has its product page also 
also i have kept the ui same as our main page 
and the nav bar footer everything is present on my shop now page 
also i have added a little hover effect on the shops card

### CODE REVIEW

**Comment by riyarane46** [comment]
@mdazfar2  please review the changes and merge my pull request . 
thankyou

**Comment by mdazfar2** [comment]
@riyarane46 update sync fork and let me know

**Comment by riyarane46** [comment]
@mdazfar2  i did there are no conflicts , you can merge my pull request

**Comment by riyarane46** [comment]
@mdazfar2 ??

**Review by mdazfar2 — APPROVED** [review]
Thank you @riyarane46

**Comment by riyarane46** [comment]
@mdazfar2 please let me know if there is anything else i can do to help

**Comment by mdazfar2** [comment]
@riyarane46 After clicking on the product the product will not show can you add the product with appropriate price

**Comment by mdazfar2** [comment]
@riyarane46 Is there any chance to add payment gateway? suppose who but the product and after successful of payment we can see that one.

**Comment by riyarane46** [comment]
@mdazfar2 , sorry i dont have experience with this task , 
if there is anything else i can do regarding frontend i will be happy to help

**Comment by mdazfar2** [comment]
Okay @riyarane46, I will ping you if there is anything for your work in frontend. Just one thing, can you work in Next.js?

**Comment by riyarane46** [comment]
@riyarane46 , no sorry i havent learned it yet.

**Comment by mdazfar2** [comment]
No problem @riyarane46.

**Pull request merged**
