### PR TITLE
Automation of project structure updation using GitHub workflows and Python scripts

### LINKED ISSUE #1031: [Feat] Automation of project structure updation using GitHub workflows and Python scripts
# Description

Currently, the project doesn't have a **project structure**. And, it would be a bit difficult for newcomers to understand the project structure completely. Also, it's difficult for anyone to manually change the project structure as it grows in size day by day. So, automating this with GitHub workflows and Python script will make the maintenance easier.

I want to add a **detailed project structure** in a separate file(redirect in README.md) for the contributors to refer to and **automate its updation process** as new files are added in the projects. This will help them refer to the structure and will make it easier for them to understand.

# Screenshots

Sample of how the workflow would be automated and the project structure after updation in readme:
image

image

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by rajdeepchakraborty-rc**
## Description
The project did not have a project structure, which would make it difficult for the newcomers to understand the project structure better. 
I have added a **detailed project structure**(redirect in README.md) in a **separate file**(since the project structure is very long and would make the README file too long making it less readable to the users) for the contributors to refer to and also **automated its updation process** as new files are added in the projects. 

**NOTE:** Every time any changes are pushed into the **main** branch, the workflow will run and then update the structure(if any changes).

This will help the contributors refer to the structure and will make it easier for them to understand where to contribute.
Also, it's difficult for anyone to manually change the project structure as it grows in size day by day. So, automating this with **GitHub workflows** and **Python script** will make the maintenance easier and help you focus on reviewing PR and assigning issues.

<br/>

## Related Issues

- Closes #1031 

<br/>

## Screenshots / videos (if applicable)

- Redirect:
image

- Project structure: [I am not sharing all the structure as it would be a lot of screenshots]
image
image

### CODE REVIEW

**Comment by rajdeepchakraborty-rc** [comment]
@mdazfar2 Please review the PR at your convenience. I would appreciate a **level3/level2** label if possible since I have added and automated the updation process.

**Comment by mdazfar2** [comment]
Hey @rajdeepchakraborty-rc, I noticed that you've created multiple commits. Could you close this PR and create a new one with just a single commit?

_Thank you!_

**Comment by rajdeepchakraborty-rc** [comment]
> Hey @rajdeepchakraborty-rc, I noticed that you've created multiple commits. Could you close this PR and create a new one with just a single commit?
> 
> _Thank you!_

@mdazfar2 It needs more than one commit since I am working on a branch. Why do you want it to be 1 commit though?

**Comment by mdazfar2** [comment]
No problem, @rajdeepchakraborty-rc, but can you answer my other reply above?

**Comment by rajdeepchakraborty-rc** [comment]
Please don't mind me asking because frankly speaking, this is a very weird request. People often say to write clearer commits to explain the changes you do to each specific file

**Comment by mdazfar2** [comment]
@rajdeepchakraborty-rc 
https://github.com/mdazfar2/Ezyshop/pull/1048#discussion_r1824675718

**Comment by rajdeepchakraborty-rc** [comment]
> @rajdeepchakraborty-rc [#1048 (comment)](https://github.com/mdazfar2/Ezyshop/pull/1048#discussion_r1824675718)

This is not opening anything for me. Could you please share it again with me?

**Comment by mdazfar2** [comment]
> > @rajdeepchakraborty-rc [#1048 (comment)](https://github.com/mdazfar2/Ezyshop/pull/1048#discussion_r1824675718)
> 
> @mdazfar2 This is not opening anything for me. Could you please share it again with me?



{BE828E44-5AA6-4E6C-BE9C-CCE3A6D92A7D}

**Comment by rajdeepchakraborty-rc** [comment]
@mdazfar2 By "fetch it from the repository" do you mean to say that I wrote down the structure of your repository myself and added a demo python file that has not done the work? 
If so then no. I will try to explain how it works. So the workflow runs and using the Python script it first generates/updates the repository structure in the **repo_sturcuture.txt** file. Then it adds the updated structure in the **Project_Strucutre.md** (To add headings and make it look neat). The workflow along with the Python script enables the GitHub bot to update the repository structure whenever there are any **changes pushed** into the **main** branch.

Also about the token, you don't have to add anything to the code that I have written. The entire reason I did this was so that you don't have to worry about this anymore and can focus on Issues and PRs. Whenever you push any changes into the main branch, the workflow will run and update the structure automatically. The only issue I was facing was that it was not updating before. Since I have started learning a bit about GitHub workflows recently, I did not know that we have to provide write permissions to every single repository. I tried resolving it and then got to know that we can add permission within the GitHub workflow to resolve this issue.

**Comment by rajdeepchakraborty-rc** [comment]
I have tried to answer your queries. Let me know if you have any other queries or if I have failed to explain anything.

**Review by mdazfar2 — APPROVED** [review]
Good to hear, @rajdeepchakraborty-rc, that you learned about workflows to solve this issue. I really appreciate your hard work. You’ll do something big in the future—best of luck! 💪🎉

**Comment by rajdeepchakraborty-rc** [comment]
> Good to hear, @rajdeepchakraborty-rc, that you learned about workflows to solve this issue. I really appreciate your hard work. You’ll do something big in the future—best of luck! 💪🎉

@mdazfar2 Thanks for the appreciation and kind words. I am glad that the contribution is helpful to the project.

**Pull request merged**
