### PR TITLE
added a dark mode for your site

### PR DESCRIPTION
**Pull request by rahulkumarparida**
i have added a dark mode for your site which will help in mor adaptive loos to the website 
**small request can you give me the labels for gssoc level 2 and hacktoberfest accepted**
it took so much long as i have to read almost 10000 code of css in you file please

### CODE REVIEW

**Comment by rahulkumarparida** [comment]
#  added a dark mode for your site
which will help in more adaptive looks to the website
**small request can you give me the labels for gssoc level 2 and hacktoberfest accepted
it took so much long as i have to read almost 10000 code of css in you file please**

**Comment by mdazfar2** [comment]
Hey @rahulkumarparida, you created a pull request directly without raising any issue. I hope you are new to open source. I request you to read the [contributing guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md), as they will help you work on open source. Please don't create pull requests directly. Thank you.

**Comment by rahulkumarparida** [comment]
# Request
**sir i had forgotten to  raise the issue  so i raised it after submitting the pull request please check**  
## issue no. [Feat] #377
**then i will create a new pull request  for this**

**Comment by mdazfar2** [comment]
Hey @rahulkumarparida, I understand, but we are not adding a dark mode feature to our website. The dark mode feature has been closed in about 15+ issues. If you don't believe me, you can check our closed issues to see how many dark mode issues have been closed. ***Thank you!***

**Comment by rahulkumarparida** [comment]
> Hey @rahulkumarparida, I understand, but we are not adding a dark mode feature to our website. The dark mode feature has been closed in about 15+ issues. If you don't believe me, you can check our closed issues to see how many dark mode issues have been closed. ***Thank you!***

Ok sir

**Pull request closed without merging**
