### PR TITLE
Added: Appropriate Page Titles

### LINKED ISSUE #1059: [BUG] Missing Page Titles
### Description

All the pages have the same title: **Ezyshop**. I want to add respective names of the pages to make the website more readable and accessible and remove any ambiguity from the minds of the user and Contributors while navigating through the web pages.

### Screenshots

image

### Any additional information?

I also want to know what plans do you have for the Teams page. I was wondering about working on it but noticed a prompt on the navbar:
image
Please share your thoughts on this matter.

### What browser are you seeing the problem on?

_No response_

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by rajdeepchakraborty-rc**
## Description

All the pages had the same title: Ezyshop. This did not reflect the purpose of the pages previously. I have updated the Page titles specific to the content on the page as below:
- `Ezyshop - Terms & Conditions` for **Terms & Conditions** Page

This will help the users navigate to the respective pages and also make the website more readable and accessible and remove any ambiguity from the minds of the user and Contributors while navigating through the web pages.

<br/>

## Related Issues

- Closes #1059 

<br/>

## Screenshots / videos (if applicable)

Here is how it looks for the pages:
image

### CODE REVIEW

**Comment by mdazfar2** [comment]
@rajdeepchakraborty-rc Please update the sync fork and let me know.

**Comment by rajdeepchakraborty-rc** [comment]
> @rajdeepchakraborty-rc Please update the sync fork and let me know.

@mdazfar2 I have synced the fork

**Review by mdazfar2 — APPROVED** [review]
Amazing work

**Comment by mdazfar2** [comment]
hey @rajdeepchakraborty-rc can you implement the same thing to our 2nd open source repo - [HelpOps-Hub](https://github.com/mdazfar2/HelpOps-hub).

**Comment by rajdeepchakraborty-rc** [comment]
> hey @rajdeepchakraborty-rc can you implement the same thing to our 2nd open source repo - [HelpOps-Hub](https://github.com/mdazfar2/HelpOps-hub).

@mdazfar2 Sure. I have opened an issue there.

**Comment by mdazfar2** [comment]
Hey @rajdeepchakraborty-rc, I have sent you a connection request on LinkedIn. Please accept it and create a LinkedIn post mentioning me as a top 3 contributor on Ezyshop if possible. _Thank you!_

**Comment by mdazfar2** [comment]
Hey @rajdeepchakraborty-rc, I have sent you a connection request on [LinkedIn](https://www.linkedin.com/in/md-azfar-alam/). Please accept it right now I am creating a LinkedIn post mentioning you as a top 3 contributor on Ezyshop if possible. _Thank you!_

**Comment by rajdeepchakraborty-rc** [comment]
> Hey @rajdeepchakraborty-rc, I have sent you a connection request on [LinkedIn](https://www.linkedin.com/in/md-azfar-alam/). Please accept it right now I am creating a LinkedIn post mentioning you as a top 3 contributor on Ezyshop. _Thank you!_

Sure.

**Pull request merged**
