### PR TITLE
Added DockerFile and Docker-compose

### LINKED ISSUE #868: [Feat] Dockerize The App
### Description

To simplify deployment and ensure consistency across environments, the application needs to be containerized using Docker. This setup will enable smooth transitions between development and production environments, providing scalability and better resource management.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by ShobhitPatra**
## Description
Added Dockerfile for containerizing the project.
Added docker-compose.yaml for easy setup and development.
Added .dockerignore to exclude unnecessary files during build.

<br/>

- Closes #868 

<br/>

### CODE REVIEW

**Comment by ShobhitPatra** [comment]
@mdazfar2 Please review it.

**Comment by mdazfar2** [comment]
Hey @ShobhitPatra, it's been over 15 minutes, and it still hasn't created an image. Can you tell me how long it usually takes to create an image and a Docker container?

image

**Comment by ShobhitPatra** [comment]
@mdazfar2 it will take time,specially the steps npm i and copy . .
I think the reason it is taking a lot of time on your machine is beacause you might not have node image locally.
Should I change the base node version to alpine as it is much lighter and will be quicker ?

**Comment by mdazfar2** [comment]
> @mdazfar2 it will take time,specially the steps npm i and copy . . I think the reason it is taking a lot of time on your machine is beacause you might not have node image locally. Should I change the base node version to alpine as it is much lighter and will be quicker ?

Hey, Node has been installed on my PC for a long time, and I use it regularly. We don't use Node for the backend; it is built on Next.js, which is serverless and makes it easy to manage both the frontend and backend.

**Comment by ShobhitPatra** [comment]
i'm talking about the docker image of node from dockerhub

**Comment by ShobhitPatra** [comment]
@mdazfar2 ,please review it

**Comment by mdazfar2** [comment]
Hey @ShobhitPatra, this time the image was created successfully, but when I created the container to run it locally, it didn't show anything. It would be great if you could help me out step by step.

<br>

{48CAF651-8BFF-421C-90FB-4E0AA486F096}

<br>

- **The container will not be created.**

image


<br>

Can you please tell me the purpose of build.yml and how we can use it for CI/CD with a step-by-step guide?

**Comment by ShobhitPatra** [comment]
@mdazfar2 What  are the logs after running docker run -p 3000:3000 ezyshop ?.If the image is built successfully ,what I would suggest you doing is 
1. run docker run -d -p 3000:3000 ezyshop.
2. then visit http://localhost:3000/

**Comment by ShobhitPatra** [comment]
whenever you merge a pull request in the main branch build.yml would allow github to automatically do these for you:
Checkout Code: Pull code from the repository.
Install Tools: Sets  Node.js for the app.
Run Tests: Ensures your code works correctly.
Build the App: basically would make sure that npm run build runs successfully  before merging the pr

**Review by mdazfar2 — APPROVED** [review]
Amazing work

**Pull request merged**
