### PR TITLE
Improved Event Title Visibility in Light Mode and Added Mailto Functionality for Email Links

### PR DESCRIPTION
**Pull request by sriharsha0x1**
#851

## Description

I have successfully resolved the issue where clicking on the email,phone number and address now directs users to their default mail application.

 Additionally, I addressed the text visibility problem in light mode by adjusting the contrast, ensuring the content remains clearly readable across different themes. You can see the improved functionality in the attached screenshot.

## Screenshots / videos (if applicable)

image

### CODE REVIEW

**Comment by mdazfar2** [comment]
Hey @sriharsha0x1, please sync your fork with the main branch and let me know once it’s done.

**Comment by sriharsha0x1** [comment]
@mdazfar2 
 I have synced my fork. Please let me know if anything else is required. Thanks!

**Comment by mdazfar2** [comment]
@sriharsha0x1, you need to update your `main` branch and create the Pull Request from the `Footer` branch. You must sync the fork of your `Footer` branch.

First, change the branch from `main` to `footer` and then click on "Update sync fork." Please see the screenshot below for better understanding.

<br>




<br/>

- Hope this time you understand please let me know if you updated sync fork in your `footer` branch.

**Comment by sriharsha0x1** [comment]
Thanks for explaining! This was my first time encountering this issue as a beginner, but I managed to sync it. However, I'm not sure why the checks failed. Could you please help me with this? Thanks for your consideration!
@mdazfar2

**Review by mdazfar2 — APPROVED** [review]
Amazing work @sriharsha0x1

**Pull request merged**
