### PR TITLE
Added features like Myorder , Cart , Wishlist

### PR DESCRIPTION
**Pull request by prvn-kumar01**
Screenshot 2024-10-06 124950
I have add the features that I mentioned earlier like myorder , Cart  , Wishlist at navbar without diturbing any other features

### CODE REVIEW

**Comment by mdazfar2** [comment]
@prvn-kumar01 mention the issue using a hashtag (#) so we can understand which issue your PR is referencing, and label your PR accordingly. Thank you!

- share recording of your changes

- and also update the sync fork.

**Comment by mdazfar2** [comment]
@prvn-kumar01 mention the issue using a hashtag (#) so we can understand which issue your PR is referencing, and label your PR accordingly. Thank you!

- Make sure when any user clicks on the cart or wishlist without logging in, an alert says "Please login first." Once the user successfully logs in, they can access the wishlist and cart buttons.

- share recording of your changes

- and also update the sync fork.

**Comment by prvn-kumar01** [comment]
when any user clicks on the cart or wishlist without logging in, an alert says "Please login first." Once the user successfully logs in, they can access the wishlist and cart buttons.

I added above feature

https://github.com/user-attachments/assets/5aa6e7e3-898b-4794-8dc9-50cf9c2a7f42

**Comment by mdazfar2** [comment]
@prvn-kumar01, instead of the above alert message, can you please make it so that the alert closes after 2 to 3 seconds?


https://github.com/user-attachments/assets/7d0ec717-bdd3-496c-9954-bb45c5576e5c

**Comment by prvn-kumar01** [comment]
I will try

**Comment by prvn-kumar01** [comment]
https://github.com/user-attachments/assets/415f5165-4dfa-4d81-a95e-c18712ea9f39
I  make it this alert only shows only for 2 seconds

**Comment by mdazfar2** [comment]
@prvn-kumar01 add alert message here and it should be full red

{39531502-D0A1-4DDC-8003-48B44D028576}

**Comment by prvn-kumar01** [comment]
According to our UI red not looks good

**Comment by prvn-kumar01** [comment]
Its already looks nice

**Comment by mdazfar2** [comment]
@prvn-kumar01 insert this in down instead of top

**Comment by prvn-kumar01** [comment]
Ok

**Comment by prvn-kumar01** [comment]
Bro but at top visibility is higher than lower so top is best place

**Comment by prvn-kumar01** [comment]
I done my all work .

**Comment by mdazfar2** [comment]
@prvn-kumar01 update your PR that's i can merge

**Comment by prvn-kumar01** [comment]
I update sync fork

**Comment by prvn-kumar01** [comment]
How can I update my PR?

**Comment by mdazfar2** [comment]
hey @prvn-kumar01 the alert message were not seen in your deployment please check that's why i can merge your PR

**Comment by prvn-kumar01** [comment]
ok I will check it

**Comment by prvn-kumar01** [comment]
Can I create new pull request??
To solve this problem

**Comment by mdazfar2** [comment]
> Can I create new pull request?? To solve this problem


@prvn-kumar01 sure closing this PR for now

**Pull request closed without merging**
