### PR TITLE
feat: Navbar links accessible when logged in (Customer)

### LINKED ISSUE #978: [BUG] 🐞 Bug Report:
### Description

Summary: The My Orders, Wish List, and Cart options should be accessible only after a user has logged in. Currently, these options are visible to all users, including those who are not logged in, which could lead to confusion. Implementing authentication/authorization for these options and placing them under a dropdown menu after login can create a more seamless experience.

1. Authentication & Authorization: The My Orders, Wish List, and Cart options should only be visible to logged-in users. These options could be placed in a dropdown menu under the user profile for better navigation and user experience.

Expected Behavior:
- When logged out, users should not see the My Orders, Wish List, and Cart options.
- After logging in, these options should be accessible and displayed in a dropdown under the profile menu.

Actual Behavior:
- The options for My Orders, Wish List, and Cart are visible to all users, regardless of their login status.

Proposed Solution:
_1. Implement authentication/authorization checks for these sections._

### Screenshots

image

### Any additional information?

_No response_

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by priyanshuverma-dev**
## Description

Shows a toaster `Please login as a Customer first` when user tries to access links like `My order`, `wishlist`, or `my cart`.

<br/>

## Related Issues

- Closes #978

<br/>

## Screenshots / videos (if applicable)

image

### CODE REVIEW

**Comment by mdazfar2** [comment]
Hey @priyanshuverma-dev, I checked, and it’s working fine, but when I successfully log in as a customer and click on Wishlist, Cart, and My Orders, these buttons are not functional. On the other hand, the buttons work on the deployed site, but in your changes, after logging in as a customer, they don’t work. Kindly check the deployment.


<br>

and do one more thing instead of `My orders`--> do only `Orders` and isntead of `Wish list`--> do only `Wishlist` I mean remove space after Wish.

**Comment by priyanshuverma-dev** [comment]
@mdazfar2 I have done fixed issue and checked locally. 
Please review again

**Comment by mdazfar2** [comment]
@priyanshuverma-dev, what did you write for your commit message this time? Please update it, as your previous commit message was good, but the second one doesn’t convey much. Try to explain it in about 6 to 7 words.

**Review by mdazfar2 — APPROVED** [review]
Amazing work @priyanshuverma-dev.

- Make sure to give ⭐ our [repo](https://github.com/mdazfar2/ezyshop)

- Join our official [Discord server](https://discord.gg/SEzpxqQG) & discuss about new features and bugs raise issue & PR accordingly.
- And also follow us on [Linkedin](https://linkedin.com/company/Ezyshopz/)

**Pull request merged**
