### PR TITLE
Height is Adjusted 

### PR DESCRIPTION
**Pull request by HeartTick**
## Description
Height of the cards in the Latest Blogs section is fixed successfully. #248 

<br/>

## Related Issues

 Height is Distinguished . 

<br/>

## Screenshots / videos (if applicable)
image

### CODE REVIEW

**Comment by HeartTick** [comment]
Let me Know if there is any change . Thank you.

**Comment by mdazfar2** [comment]
hey @HeartTick please update sync fork as soon as possible

**Comment by HeartTick** [comment]
@mdazfar2  This PR is now up to date can you please Review it once Thank  You.

**Comment by mdazfar2** [comment]
Hey @HeartTick, sorry for the late reply. I was busy due to my health condition. Actually, your pull request is on the previous version of the website, which was in HTML and CSS. We have now successfully converted our code to Next.js and Tailwind CSS for back-end integration and payment gateway. So please don't be discouraged; I'm closing this pull request. You can work on any new issue, and I'll be happy to assign it to you. Make sure to join our [Discord server](https://discord.gg/Rg8T5gtE) for the latest announcements regarding the website and features as well. _Thank you!_

**Pull request closed without merging**
