### PR TITLE
adding a bit more bottom padding to the footer

### PR DESCRIPTION
**Pull request by DivyaJyothi9**
added a bit more bottom padding to the footer ,so the design doesn't feel too "tight" against the bottom edge of the browser.

### CODE REVIEW

**Comment by DivyaJyothi9** [comment]
Thank you sir!!

**Comment by DivyaJyothi9** [comment]
@thakuratul2  I wanted to inform you that my recent pull request was accepted and merged, but it was not assigned to me. As I'm still a novice with contributions, I was a bit confused about the process for submitting a pull request.Sir, it was my first pull reuest. I kindly request you to assign the PR to me so that the points can be added.
Kindly please do it sir!!

Thank you for your understanding and assistance!

**Comment by mdazfar2** [comment]
Done @DivyaJyothi9

**Comment by DivyaJyothi9** [comment]
Thank you @mdazfar2 !!

**Comment by mdazfar2** [comment]
@DivyaJyothi9 - please give ⭐ our repo

- Join our official [Discord server](https://discord.gg/SEzpxqQG) & discuss about new features and bugs raise issue & PR accordingly.
- And also follow us on [Linkedin](https://linkedin.com/company/Ezyshopz/)

**Comment by mdazfar2** [comment]
@DivyaJyothi9 yes the points will be added to the leaderboard! No worries.

**Comment by DivyaJyothi9** [comment]
Got it..Thank you sir!!

**Pull request merged**
