### PR TITLE
Fixes the issue On buttons

### PR DESCRIPTION
**Pull request by rupeshv2121**
Fixes the issues on the button and add some small css where it to the other portion of website
Add web logo on the footer , previously it is not there

Issue Number :  #316

### CODE REVIEW

**Comment by rupeshv2121** [comment]
Pls Add label under hacktoberfest-accepted and gssoc-ext and level

**Comment by mdazfar2** [comment]
hey @rupeshv2121 Please share demo video before creating pull request

**Comment by rupeshv2121** [comment]
Ok Sir @mdazfar2

**Comment by rupeshv2121** [comment]
Uploading Recording 2024-10-09 173741 (1).mp4…

@mdazfar2 Sir pls check

**Comment by mdazfar2** [comment]
@rupeshv2121, I'm unable to see your recording here. Please share it as soon as possible. If you don't share it soon, I'll have to merge another PR, which might cause conflicts with yours. Please also remember to update your sync fork.


image

**Comment by rupeshv2121** [comment]
@mdazfar2 sir can i send video on Discord ?

**Comment by mdazfar2** [comment]
**Hey @rupeshv2121, check your conflict. It would be great if you close this PR and create a new one after syncing the fork. Please do it as soon as possible as I want to merge your PR by today morning. Thank you!**



<br>

image

**Comment by rupeshv2121** [comment]
Screenshot_20241010-055825
Sir no conflicts @mdazfar2

**Comment by mdazfar2** [comment]
Ooho @rupeshv2121, you forgot to update the sync fork again. Look at the screenshot below of what I mentioned earlier. Why do you keep forgetting? I'm not closing your Pull Request. If it were someone else's PR, I would have had to close it. I'm not closing it only for you.

<br>


image

**Pull request closed without merging**
