### PR TITLE
Fixes the Issues

### PR DESCRIPTION
**Pull request by rupeshv2121**
Issues In:
1. Alignment of Contact Us
2. Extra Padding in Footer section in Copyright block.

Issue Number : #210 
Please add labels gssoc-24-ext and hacktoberfest

### CODE REVIEW

**Comment by rupeshv2121** [comment]
@mdazfar2 sir pls review my PR asap and Merge it

**Review by mdazfar2 — APPROVED** [review]
thank you @rupeshv2121

**Comment by rupeshv2121** [comment]
Sir pls add labels

**Comment by mdazfar2** [comment]
done @rupeshv2121.

- Hope you star this repo

**Pull request merged**
