### PR TITLE
 Some Changes in features.tsx file

### PR DESCRIPTION
**Pull request by ansiace**
This pull request addresses the issue where the hover effect was missing on the cards. Additionally, I've enhanced the design of the "Our Facilities" cards by adding a `box-shadow` and `transform scale` on both home and about section to improve the visual appeal and interactivity.

### Changes Made
- **Hover Effect**: Implemented a smooth hover effect on all cards, making the UI more dynamic and user-friendly.
- **Box-Shadow and Transform**: Added `box-shadow` and `transform scale` to the "Our Facilities" cards, improving the design by adding depth and making the hover experience more engaging.
  
### Visual Enhancements
- Cards now respond with a subtle scale effect and shadow on hover, providing a more interactive and visually appealing experience.
  
  

https://github.com/user-attachments/assets/fd2e5de5-4461-4ddc-92a1-2d7bdd32522d

### CODE REVIEW

**Comment by ansiace** [comment]
- closes #689

**Comment by ansiace** [comment]
Hi @mdazfar2 , I hope you're doing well! I've successfully addressed the box-shadow and transform scale and i created one more issue in this project  that " our facilities  " should have centered that issue is resolved now when the code is converted to tailwind and next.js. Both issues have been resolved to improve the UI performance and interactivity.

Given the scope of changes and the additional fixes made, I would like to kindly request the Level 2 tag for this contribution. Thank you for your consideration!

**Review by mdazfar2 — APPROVED** [review]
Lgtm 🎉

**Comment by ansiace** [comment]
Thank you @mdazfar2 for merging my pull request! I really appreciate your quick review and action. I'm glad I could contribute, and I look forward to collaborating on more issues in the future!

**Pull request merged**
