### PR TITLE
Corrected the problem in PR #168

### PR DESCRIPTION
**Pull request by Priyesh017**
## Description
When solving the issue #154, I made two silly mistake in PR #168

- One is while removing unnecessary comments and removed the else statement in Password Visibility toggle function in register.js file.

- Another is in the style of the navbar, wrote a nested media query [Allowed in SCSS not in normal CSS] in the register.css file. 

This PR is to solved those problems made previously.

@Kavita1928 I have corrected the conflicting branch.

> Please review this PR and notify me if any further changes are required.

<br/>

## Related Issues

Corrected the problem in PR #168

- Corrected the Password Visibility Toggle error.
- Corrected the Navbar style from Nested CSS to Normal CSS [Media Query].

<br/>

## Short Video of the Solution
https://github.com/user-attachments/assets/6b7418b6-688d-4e41-af1b-4e4cd50ccab8

### CODE REVIEW

**Comment by Kavita1928** [comment]
@Priyesh017 resolve the issue soon

**Comment by Priyesh017** [comment]
> @Priyesh017 resolve the conflict soon
@Kavita1928 , the conflict has been resolved. You can merge this branch.

**Comment by Priyesh017** [comment]
> > @Priyesh017 resolve the conflict soon 
@Kavita1928 , the conflict has been resolved. You can merge this branch.

**Review by mdazfar2 — APPROVED** [review]
Amazing work @Priyesh017 


- Actually, I need to reach a total of 128 stars to get the Starstruck x2 badge achievement on my GitHub. Can you please help by Star our [repository](https://github.com/mdazfar2/ezyshop/)? ⭐

**Comment by Priyesh017** [comment]
> Amazing work @Priyesh017
> 
> * Actually, I need to reach a total of 128 stars to get the Starstruck x2 badge achievement on my GitHub. Can you please help by Star our [repository](https://github.com/mdazfar2/ezyshop/)? ⭐

Thank you for your kind words! I have already starred your repository. Hope you achieve your goal quickly. All the best!

**Pull request merged**
