### PR TITLE
[FIX] Contact Us Page Alignment Fixed

### LINKED ISSUE #257: [BUG] Contact Us Align Issue
## Alignment issue

- Address, Email, Phone and opening hours texts are not aligned with icons.

### Screenshots

image

### Any additional information?

_No response_

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by 4F24L**
## Contact Us Page Alignment Fixed
- Fixes #257 

### Before : 
image

### After ✅ :
image

### Please add hactoberfest and GSSoC24 label.

### CODE REVIEW

**Comment by mdazfar2** [comment]
@4F24L checkout this it looks weird 

{F6A6D905-71F2-461C-B786-A75E55C88538}

**Comment by 4F24L** [comment]
Increasing the height !!

**Comment by mdazfar2** [comment]
yes @4F24L please look another page height and matching to the contact page

**Comment by 4F24L** [comment]
Okay

**Comment by 4F24L** [comment]
check @mdazfar2

**Review by mdazfar2 — APPROVED** [review]
thank you @4F24L

**Comment by 4F24L** [comment]
Thanks for the level upgrade.

please assign me for further issues. I'll be glad to fix new bugs on your project.

**Pull request merged**
