### PR TITLE
Added New Contributors Page

### LINKED ISSUE #820: [Feat] add contributor or team page at footer
### Description

add contributor or team page at footer will look more proeffesional

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by IkkiOcean**
#### Description
This PR introduces a new Contributor Page designed to showcase contributors to the project. The page is built with responsiveness in mind, ensuring a seamless experience across both desktop and mobile devices. Additionally, the design is compatible with both light and dark modes, maintaining visual consistency regardless of user preferences.

- Closes #820 

#### Features
- **Responsive Design**: The layout adjusts fluidly to different screen sizes, enhancing usability on both desktop and mobile devices.
- **Light and Dark Mode Compatibility**: The page automatically adapts its color scheme based on the user's selected theme, providing a consistent user experience.
- **Consistent Design**: The design follows the specifications provided for uniformity across the application.

#### Changes Made
- Revamped`contributors/pages.tsx`
- Revamped `ContributorCard.tsx` component.
- Added CSS styles for responsiveness and theme adaptation.

#### The given design
382243445-d44f3ad8-1aca-4e82-8e85-f3690077524e

#### Video

https://github.com/user-attachments/assets/cb4e9939-5978-464d-8985-6a1283138d43

#### Checklist
- [x] Code is clean
- [x] Responsive design is implemented and tested.
- [x] Light and dark mode compatibility is ensured.

### CODE REVIEW

**Comment by IkkiOcean** [comment]
@mdazfar2 hope you like the implementation, and please mention if you have any other issue up for grab. Happy to contribute :)

**Comment by mdazfar2** [comment]
Hey @IkkiOcean Right now, there is a deployment error with your pull request. Please check the screenshot below as proof.

When I merged your PR, the changes didn't reflect on our deployed site. Did you check `npm run lint` while committing?

I hope you read our [contributing guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md).


<br>

image

**Comment by IkkiOcean** [comment]
> Hey @IkkiOcean Right now, there is a deployment error with your pull request. Please check the screenshot below as proof.
> 
> When I merged your PR, the changes didn't reflect on our deployed site. Did you check `npm run lint` while committing?
> 
> I hope you read our [contributing guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md).
> 
> 
> <br>
> 
> image
> 

I will fix it right away, it's a minor bug

**Comment by IkkiOcean** [comment]
@mdazfar2 check now

**Comment by mdazfar2** [comment]
@IkkiOcean Wow, that's amazing! You created exactly what I wanted, but there are a few changes needed. I'll explain below.

Write `Open-Source Contributor` everywhere instead of `contributions number which you kept` Check out the screenshot below for better understand.

<br>

image

<br>

And one more thing, add some space between the username and the profile pic, and just write `Contributions 135`. Make sure not to create any boxes; simply write `Contributions` with the number for each contributor, fetched from GitHub. Check out the screenshot below for reference.

<br>

image

<br>

> And kindly convert all the images to .webp format.

<br>

> [!NOTE]
> And **Vivek**, the most important thing is that the fetching doesn't seem to be working correctly from the GitHub contributors. Please check our contributors after clicking the `Contributors` button. Open our [Ezyshop repository](https://github.com/mdazfar2/Ezyshop), click on `Contributors`, and then compare it with your fetched contributor page which you create now. I hope you find what I noticed. See the screenshot below.

<br>

image



---

<br>

- Add a hover effect on each contributor's profile image, and make sure that clicking on a profile redirects to the contributor's GitHub profile. Hope you understand.

> & write valid commit message.

- Don't worry take your time to complete all these.

**Comment by IkkiOcean** [comment]
@mdazfar2 okay. I dont know whats wrong with the GitHub api to fetch contributors list but I will try to fix it, and the other issues you mentioned

**Comment by mdazfar2** [comment]
> one more thing:
> you want structure like this right:

> Contributions 135
> Name of the contributor
> Open Source Contributor

<br>

Exactly @IkkiOcean, but there is no box for contributor 135. Just write it simply and add a cursor pointer on it.

**Comment by IkkiOcean** [comment]
> > one more thing:
> > you want structure like this right:
> 
> > Contributions 135
> > Name of the contributor
> > Open Source Contributor
> 
> 
> Exactly @IkkiOcean, but there is no box for contributor 135. Just write it simply and add a cursor pointer on it.

and cursor pointer redirecting to GitHub profile on clicking? sam with the profile pic right?

**Comment by mdazfar2** [comment]
> and cursor pointer redirecting to GitHub profile on clicking? sam with the profile pic right?



<br>


No @IkkiOcean, it should open every contributor's page to show what type of things they contributed. Check out the link below for reference.

https://www.helpopshub.com/team

<br>

When you open the link above, scroll down and click on "Contributions." You’ll understand. I’m also sharing a screenshot below showing where to check after clicking.

<br>




<br>

- Let me know if there is any queries regarding this.

**Comment by IkkiOcean** [comment]
https://github.com/user-attachments/assets/1657bb90-0891-4702-9a9c-36f184d528d7


### Updates:
1)  Profile hover effect with redirection on click
2) "Open-Source Contributor" Label
3) Clicking on contributions redirects to the commits of the contributor.
@mdazfar2 check it now.

**Comment by IkkiOcean** [comment]
@mdazfar2  I will find out about the issue you are facing with GitHub providing old data through the api tomorrow. For now, if you dont have any issue with the implementation, please merge it. Hope you liked it.

**Comment by mdazfar2** [comment]
@IkkiOcean It is nice, but give more space between "Contributions" and the contributor's name.

**Comment by IkkiOcean** [comment]
> @IkkiOcean It is nice, but give more space between "Contributions" and the contributor's name.
> 
> 

Okay

**Comment by mdazfar2** [comment]
@IkkiOcean, apply the hover effect you used on the top 3 to all other contributor profiles as well.

Tell me one thing: is it also fetching for the top 3 contributors? Suppose someone contributes more than the current top 3; they should appear in the top 3, right?

**Comment by IkkiOcean** [comment]
> @IkkiOcean, apply the hover effect you used on the top 3 to all other contributor profiles as well.
> 
> Tell me one thing: is it also fetching for the top 3 contributors? Suppose someone contributes more than the current top 3; they should appear in the top 3, right?
> 
> 

It's fetching for the contributors only but I have filtered the top three as it's better to not use another get request, as it will increase load time

**Comment by IkkiOcean** [comment]
It will dynamically put top 3 contributors while also ignoring you

**Comment by mdazfar2** [comment]
@IkkiOcean 
Right now **Rajdeep** has a total of 17 contributions. If, in the future, you complete `18 contributions`, will **you** automatically appear in the top 3 contributors?

**Comment by IkkiOcean** [comment]
Yeas. It's simply based on the ranking provided by the github @mdazfar2

**Comment by mdazfar2** [comment]
> Yeas. It's simply based on the ranking provided by the github @mdazfar2 


Ohw! Thank's, I wanted to confirm this.

**Comment by IkkiOcean** [comment]
Usually GitHub takes time to update the info in this API(as a rate limit) ,but your repo isn't receiving correct info. You might wanna check your insight section or smtg. I will also look into it as its also happening in another repo

**Comment by IkkiOcean** [comment]
@mdazfar2 pushed the commit with same effect and space between name and contributions

**Review by mdazfar2 — APPROVED** [review]
Amazing work, @IkkiOcean. ✨

I mentioned converting images to .webp format. Don’t worry; I’ll merge this PR, but please try to implement that in the next one. Also, please display only 4 contributor profiles per row; you currently have 5. Having 4 profiles per row will leave some space on the right and left sides, which looks more professional and neat. If you work on a new issue in this repo, please update this as well. By the way, everything looks fantastic.

And please don't forget to give a star to our repo ⭐

- _Thank You!_

**Comment by IkkiOcean** [comment]
@mdazfar2 I actually made it responsive for mobile and desktop view so it automatically accommodates the profiles per row.But I can implement 4 per row logic in the next issue if you want with the .webp format conversion also

**Comment by IkkiOcean** [comment]
@mdazfar2 do let me know, if you have any other issues up for grab, or anything you wanted to implement.

**Comment by mdazfar2** [comment]
@IkkiOcean 🔊

https://github.com/user-attachments/assets/0de74fc1-c614-477f-8fa3-e0fa96ab3bd6

**Comment by IkkiOcean** [comment]
> @IkkiOcean 🔊
> 
> https://github.com/user-attachments/assets/0de74fc1-c614-477f-8fa3-e0fa96ab3bd6
> 
> 

Sure i will raise the issue

**Pull request merged**
