### PR TITLE
Fixed: Latest Article from blog Card in home page

### PR DESCRIPTION
**Pull request by coderKrysio**
#294 Fixed: Latest Article from blog Card in home page is completed please check and merge it.
@mdazfar2 

Screenshot 2024-10-08 111231

### CODE REVIEW

**Comment by mdazfar2** [comment]
@coderKrysio resolve your conflict and update sync fork

**Comment by coderKrysio** [comment]
conflict resolved

**Comment by coderKrysio** [comment]
if everything is working alright, please assign me the issue first and then merge accordingly

**Review by mdazfar2 — APPROVED** [review]
Amazing work @coderKrysio

**Comment by MastanSayyad** [comment]
Hey @mdazfar2 **Program Manager** this side

Add `hacktoberfest` label to issues and `hacktoberfest-accepted` to Merged PRs also i dont think this PR is worth `level 1` add `level 2` label

Also make sure you add Hacktoberfest labels to only quality PRs.

**Pull request merged**
