### PR TITLE
Added Contact us page

### LINKED ISSUE #437: [Feat] there is no Contact page in Nextjs version of the website
### Description

there is no Contact Page page in Nextjs version of the website

image

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by ShivanshPlays**
## Description

Added Contact us page

<br/>

## Related Issues

- Closes #437 

<br/>

## Screenshots / videos (if applicable)

https://github.com/user-attachments/assets/bf17b746-8484-4a1a-9a76-86704b89d0be

### CODE REVIEW

**Comment by mdazfar2** [comment]
@ShivanshPlays go ahead.

**Review by mdazfar2 — APPROVED** [review]
Great work!

**Review by MastanSayyad — COMMENTED** [review]
does it have backend or any email sending functionality?
if no then this can only have `level 2` @mdazfar2

**Comment by mdazfar2** [comment]
Hey @MastanSayyad, I see that you’ve mentioned me a lot in PRs and issues. I understand the importance of responsiveness and agree that contributors should ensure pages are fully responsive if they know how; otherwise, PRs solely for responsiveness won’t be valid for points.

But let me clarify something: **Shivansh** created a fully responsive Contact Us page while working on the frontend only. Adding functionality falls under backend work, so creating a complete page with Next.js and TypeScript—along with responsiveness—is challenging and was rated as a level 3 task by Sanjay Sir previously.

You mentioned above he should also add backend functionality. However, it’s not feasible to complete both frontend and backend in a single PR. He focused on the frontend first and is now working on backend functionality.

- What I mean is that creating a full page with this level of effort isn’t easy. He dedicates 1-2 days to many level3 label PR, and based on our LinkedIn discussion, he spends over 20+ hours on much PR. Please see the screenshot below as proof.




**Mastan**, I kindly request that you don’t discourage him or reduce the level, as he has genuinely put in hard work for each PR and is not spamming.

***Thank you.***

**Comment by MastanSayyad** [comment]
Hi @mdazfar2,

I noticed multiple PRs in your repository that have been labeled as level 3, and some appear to be repetitive. We are reducing the level on a few of these PRs because each level 3 label significantly impacts the leaderboard for contributors. While some PRs indeed deserve level 3, it seems that for others, a level 2 would be more appropriate. For example, creating a fully responsive contact page and receiving level 3 for it is justified, but adding level 3 again for simply making that page responsive is not fair. Responsiveness should ideally be part of the initial page creation it is devs basic responsibility 

I'm not discoraging anyone, that's why I said to add level 2 not level 1 for some who needs level 1 I have mentioned the reasons too, it is not about spamming...level 3 to maxlimum PRs is questionable, levels should have some meaning 

Please review the mentioned PRs and let me know why the level adjustments can’t be made,  We’re applying these reductions across all contributors on the leaderboard, so it’s not directed only at one person. 

he is a rank 2 contributor and I'm following the gssoc guidelines.  When reviewing, we only see the codebase, so it would help if PRs had clear descriptions outlining what changes were made. This transparency would reduce the need for further questions and requests.

Also, I’ve asked several times for you to add me as a collaborator, as this access would assist me in reviewing contributions, It is not easy to review PRs of multiple contributors, to ensure fairness and balance I'm doing this. You said you have sent me the invitation but I  didn’t receive the invitation you sent, so if you could kindly resend it, I’d appreciate it.

### Guidelines: 

image

image

---

@ShivanshPlays, your contributions are impressive, and we recognize your hard work. However, since you’re ranked 2, we are taking a closer look at a few PRs to ensure fair scoring. I’d suggest making each PR more detailed, with explanations of your work. This gives reviewers better insight into your efforts. If you think I'm discouraging you then feel free to add your justification.

For reference, here’s an example of a well-documented PR from my time as a GSSoC contributor:

image

**Comment by ShivanshPlays** [comment]
@MastanSayyad I understand and respect the guidelines, but I request you to kindly provide me with 1 days time, by tomorrow morning....all my PRs will contain the justification of the work and level done, I have been doing the same all day. I assure you that none of my PRs are invalid and if found invalid after my detailed description then I would have no issue if you reduce its point.

TL'DR is please give me 1 days time to assign proper justifications for the level.

thankyou for being cooperative @MastanSayyad  @mdazfar2

**Comment by mdazfar2** [comment]
Alright! @MastanSayyad, I understand what you’re saying. I am reducing the label, and as you requested, I’m inviting you as a collaborator. Please check and accept the invitation. See the screenshot below as proof.

<br/>

{42D2D50D-5155-4DFB-BA85-B267E6D6F65C}

<br>

**Mastan**, please reply to one question as well: what level of points will be assigned for creating pull request functionality? I believe it would be level 1 according to you, right?

- I think it might be difficult to have a real-time conversation due to the delays in our responses. If you're comfortable, we could discuss on [Discord](https://discordapp.com/users/877531143610708028) or [LinkedIn](https://linkedin.com/in/md-azfar-alam/) for a more efficient exchange.

**Comment by MastanSayyad** [comment]
@mdazfar2 accepted but no need to remove the labels, @ShivanshPlays review is already completed on 26th Oct midnight

**Pull request merged**
