### PR TITLE
Added Visibility Password Toggle and Adjusted the Margin Top of the Sign-in/Login Card

### PR DESCRIPTION
**Pull request by Priyesh017**
### **Changes Done**

- **Password Visibility Toggle:** 
Implemented a password visibility toggle feature on the sign-in/login form, allowing users to toggle between viewing and hiding their password input. This enhances user experience by providing an optional way to check the password they are entering.

- **Margin Adjustment:** 
Adjusted the margin-top of the sign-in/login card for better alignment and spacing on the page, improving the overall visual layout.

Issue #154 is solved.

Please review my code and let me know if any changes are required.

### CODE REVIEW

**Review by mdazfar2 — APPROVED** [review]
great work @Priyesh017

**Comment by Priyesh017** [comment]
@mdazfar2 I would like to correct my two mistakes while contributing to issue #154 

- **First:** When removing unnecessary comments I by mistake removed an else statement from the Visibility Toggle function which I want to correct.
- **Second:** I wrote a nested Media Query in CSS which is not valid, so I want to correct it.

Please allow me to correct my mistakes.

**Comment by mdazfar2** [comment]
@Priyesh017, open the PR again and try to create it correctly. Take your time and submit the PR, no worries, we are here to help you.

- feel free to reach out to me on [Discord](https://discordapp.com/users/877531143610708028) or [LinkedIn](https://linkedin.com/in/md-azfar-alam/).

**Comment by Priyesh017** [comment]
@mdazfar2 Thanks for helping me out.

**Pull request merged**
