### PR TITLE
Footer social links updated as per your information

### PR DESCRIPTION
**Pull request by 9AB5**
Description:
The social links in the footer of site has been updated according to your information

Screenshot:
Screenshot 2024-10-07 164133

### CODE REVIEW

**Comment by mdazfar2** [comment]
why did you update on only homepage?? @9AB5 update this every page

**Comment by 9AB5** [comment]
@mdazfar2 Okay, I will update this in every page

**Comment by mdazfar2** [comment]
@9AB5 You updated only the homepage, but as you know, the footer is available on all pages, so please update the footer on every page.

**Comment by 9AB5** [comment]
@mdazfar2 I have updated the footer social links to every page of site
Screenshot:
Screenshot 2024-10-07 232332
Screenshot 2024-10-07 232343
Screenshot 2024-10-07 232354
Screenshot 2024-10-07 232404
Screenshot 2024-10-07 232413

**Comment by mdazfar2** [comment]
@9AB5 update your sync fork and also resolve your conflict

**Comment by 9AB5** [comment]
@mdazfar2 Okay, I will resolve the conflict and sync fork

**Comment by 9AB5** [comment]
@mdazfar2 I have resolved the conflicts

**Comment by mdazfar2** [comment]
Hello @9AB5, can you please close your PR as it is overlapping and has many conflicts?

**Pull request closed without merging**
