### PR TITLE
Fix the Logos Issue

### PR DESCRIPTION
**Pull request by rupeshv2121**
I fix all the Logos issue in the MEET OUR FOUNDER section and relevant social media link to the respective logo
Issue Number : #206 

Pls add label gssoc-ext , hacktoberfest-accpeted

### CODE REVIEW

**Comment by mdazfar2** [comment]
hey @rupeshv2121 update sync fork and let me know.

**Comment by mdazfar2** [comment]
@rupeshv2121 please let me know if you update your PR or not

**Comment by rupeshv2121** [comment]
Yes

**Comment by mdazfar2** [comment]
@rupeshv2121 Again it is not updated. I apologize, but I need to close this pull request for now. Please don't be discouraged!



image

**Comment by rupeshv2121** [comment]
Sir Why u closed this

**Comment by rupeshv2121** [comment]
in hacktoberfest account it is showing rejected

**Pull request closed without merging**
