### PR TITLE
Adding hover effect services part 

### PR DESCRIPTION
**Pull request by vijaychandra1910**
#234 Adding hover effect in service part is completed please check and merge it.
@mdazfar2 

https://github.com/user-attachments/assets/8ae9d5b3-fc52-40a5-9e7c-cb1cc275975f

### CODE REVIEW

**Comment by mdazfar2** [comment]
Hey @vijaychandra1910, why did you create and close the PR? I just asked you to update your branch so that I can merge your PR.

**Comment by vijaychandra1910** [comment]
why I hvn't get the tag of #234  after competing this.

**Comment by vijaychandra1910** [comment]
@mdazfar2  completed please check

**Comment by mdazfar2** [comment]
@vijaychandra1910 It is not updated yet please update

**Comment by mdazfar2** [comment]
Hey @vijaychandra1910, sorry for the late reply. I was busy due to my health condition. Actually, your pull request is on the previous version of the website, which was in HTML and CSS. We have now successfully converted our code to Next.js and Tailwind CSS for back-end integration and payment gateway. So please don't be discouraged; I'm closing this pull request. You can work on any new issue, and I'll be happy to assign it to you. Make sure to join our [Discord server](https://discord.gg/Rg8T5gtE) for the latest announcements regarding the website and features as well. _Thank you!_

**Pull request closed without merging**
