### PR TITLE
SHOP NOW cards are made more visually appealing

### PR DESCRIPTION
**Pull request by NIKITABARANWAL890**
Issue no. #460 
"Shop now" cards are poorly designed.

@Kavita1928 ma'am
@mdazfar2 sir
I've made all the possible changes to improve the cards. Kindly let me know, if any further adjustments are needed?

**Before Hover:**

Screenshot 2024-10-12 145603

**After Hover**

Screenshot 2024-10-12 150145

**Changes made are**:

1.Improved the Card Layout to make it look more beautiful.
2.Replaced all the blurred images with high-quality images.
3.Added 'save for later' button for more feature.
4.Formatted the cost of each product in 'en-IN' format, where commas are used.
5.**Hovering over each product image changes the image.**

_If you liked the changes, kindly label it with a higher level._

### CODE REVIEW

**Comment by mdazfar2** [comment]
hey @NIKITABARANWAL890 please share the screen record of your changes

**Comment by NIKITABARANWAL890** [comment]
> hey @NIKITABARANWAL890 please share the screen record of your changes


https://github.com/user-attachments/assets/314fe10b-cb95-4025-835c-b5225cb38a53

@mdazfar2 sir

**Comment by NIKITABARANWAL890** [comment]
@mdazfar2 sir i've resolved all the conflicts, kindly review once and let me know if any further changes are supposed to be done.

_If you liked my work, please label it with a higher level._

**Comment by NIKITABARANWAL890** [comment]
@mdazfar2 kindly review the PR

**Review by mdazfar2 — APPROVED** [review]
Amazing work @NIKITABARANWAL890

**Pull request merged**
