### PR TITLE
Added Sticky Navbar

### PR DESCRIPTION
**Pull request by Kratika-Solanki**
Co-authored by: Kratika Solanki <kratikasolanki3669@gmail.com>

### CODE REVIEW

**Comment by Kratika-Solanki** [comment]
issue no. #48

**Comment by mdazfar2** [comment]
@Kratika-Solanki please update the sync fork and let me know

**Review by mdazfar2 — APPROVED** [review]
thank you @Kratika-Solanki

**Comment by mdazfar2** [comment]
hey @Kratika-Solanki can you fix the image it is not earlier it occur during the merged of your PR #112.

{E1BB3559-3A47-4DA2-9682-B86AE0CBBA18}

**Comment by Kratika-Solanki** [comment]
Okay @mdazfar2, let me check it from my end.

**Comment by Kratika-Solanki** [comment]
@mdazfar2, I have made the changes, do I need to commit those changes and again raise a new PR?

image

**Comment by mdazfar2** [comment]
@Kratika-Solanki, it would be great if you could fix the image size in the middle for full view on the landing page as per your design.

No, you need to create a separate PR because the previous one has been merged, so you will have to create the PR again.

**Pull request merged**
