### PR TITLE
Fix the Visibility Issue in Buttons

### PR DESCRIPTION
**Pull request by rupeshv2121**
I fix the issues in the buttons on the whole website and make change in font icon of phone in footer.
 
Issue Number : #399 

https://github.com/user-attachments/assets/8029a828-156a-4982-9979-5ab84b432eea

pls add label gssoc-ext, hacktoberfest-accepted

### CODE REVIEW

**Comment by mdazfar2** [comment]
@rupeshv2121 It's been 3 days, and I cannot merge your PR because you are late in responding to us. It's late, so I merged someone else's PR. You need to update your fork and resolve the conflict.

**Comment by rupeshv2121** [comment]
Sir this is not good because I resolve issues with 5-6 hrs but you respond after sometime that's why it take 3 days hope so you understand me

**Comment by Kavita1928** [comment]
@rupeshv2121 solve this logo issue to be merged
Screenshot 2024-10-11 094719

**Comment by rupeshv2121** [comment]
@Kavita1928 mam pls add label gssoc-ext and hacktoberfest-accpeted and level which you want

**Pull request merged**
