### PR TITLE
Added multilingual option

### LINKED ISSUE #457: [Feat]: Add Multilingual Support
### Description

I will add multilingual support to the website so that all pages' content can be translated to different selected language in according to the language selected by the user.

Benefits
- Improved User Experience: Users can navigate in their preferred language.
- Scalability: Easily add new languages in the future.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by PavanTeja2005**
## Description
I have added an option to translate all website into various languages,

<br/>

## Related Issues

Closes #457 

<br/>

## Screenshots / videos (if applicable)
image
image

### CODE REVIEW

**Comment by PavanTeja2005** [comment]
@mdazfar2 Please review the PR

**Comment by PavanTeja2005** [comment]
@Kavita1928 please check this too

**Comment by mdazfar2** [comment]
@PavanTeja2005, can you please share the demo video showing how it is working?

**Comment by mdazfar2** [comment]
Hey @PavanTeja2005, sorry for the late reply. I was busy due to my health condition. Actually, your pull request is on the previous version of the website, which was in HTML and CSS. We have now successfully converted our code to Next.js and Tailwind CSS for back-end integration and payment gateway. So please don't be discouraged; I'm closing this pull request. You can work on any new issue, and I'll be happy to assign it to you. Make sure to join our [Discord server](https://discord.gg/Rg8T5gtE) for the latest announcements regarding the website and features as well. _Thank you!_

**Pull request closed without merging**
