### PR TITLE
responsive login signup page issue #230

### PR DESCRIPTION
**Pull request by AyushSharma72**
i made the login page responsive for small screen under 768px

Screenshot (172)

Screenshot (173)

Screenshot (174)

Screenshot (175)

**please add labels gssoc-ext and level2 on this PR before merging**

### CODE REVIEW

**Comment by mdazfar2** [comment]
@AyushSharma72 what about navbar in mobile responsive??

**Comment by AyushSharma72** [comment]
> @AyushSharma72 what about navbar in mobile responsive??

Okay I add a hamburger icon but will you mark this as level 3 then ??

**Comment by AyushSharma72** [comment]
> @AyushSharma72 for responsiveness and all is only considered level 1, but I gave you level 2. I can give you level 3, but when the GSSoC team coordinator reviews it, your points might be reduced to level 1. However, if you still want, I can give you level 3.

let it be i will make the navbar responsive on level 2 only

**Comment by AyushSharma72** [comment]
> @AyushSharma72 what about navbar in mobile responsive??

Screenshot 2024-10-07 213513

Screenshot 2024-10-07 213521

completed

**Comment by mdazfar2** [comment]
hey @AyushSharma72 kindly update sync fork and let me know

**Comment by AyushSharma72** [comment]
> hey @AyushSharma72 kindly update sync fork and let me know

Update @mdazfar2

**Comment by mdazfar2** [comment]
It is not updated @AyushSharma72 update your this branch `ResponsiveLoginPage`

<br/>



image

**Comment by AyushSharma72** [comment]
> It is not updated @AyushSharma72 update your this branch `ResponsiveLoginPage`
> 
> 
> image

Ok I Will do it tomorrow

**Comment by AyushSharma72** [comment]
> It is not updated @AyushSharma72 update your this branch `ResponsiveLoginPage`
> 
> 
> image

completed  please check @mdazfar2

**Review by mdazfar2 — APPROVED** [review]
Awesome work @AyushSharma72

**Comment by AyushSharma72** [comment]
> Awesome work @AyushSharma72

thanks @mdazfar2

**Pull request merged**
