### PR TITLE
Fixed View Password Feature On Sign Up Form : #465

### PR DESCRIPTION
**Pull request by Preethii-R**
Hello,

In the website, here was no feature allowing users to toggle the visibility of the password and confirm password fields, which could lead to input errors and hinder user experience.

To resolve this issue, I implemented a password visibility toggle feature using the <i> HTML tag to represent an eye icon.

-  I reviewed the existing code to identify the locations of the password fields and understand their current implementation.
-  I conceptualized a user-friendly solution that would enable users to click an eye icon to reveal or conceal their password input.
-  I added the eye icon using the <i> tag and integrated JavaScript functionality to handle the click event, allowing the password 
   field to switch between 'text' and 'password' types.

Screenshot (24)

Screenshot (25)

Screenshot (26)

Screenshot (27)

### CODE REVIEW

**Comment by mdazfar2** [comment]
@Preethii-R remove the lock icon and add the visible icon and make sure the color of that icon should be the same as website.


- Preethii, I need to reach a total of 128 stars to get the Starstruck x2 badge achievement on my GitHub. Can you please help by Star our [repository](https://github.com/mdazfar2/ezyshop/)? ⭐

**Comment by Preethii-R** [comment]
Hello,
I have resolved the conflicts. Please check it out.

https://github.com/user-attachments/assets/619c6519-92c6-4e75-abbd-7806d501bc96

**Comment by Preethii-R** [comment]
Please check the changes I have mase and guide me through the next steps.

**Comment by mdazfar2** [comment]
Hey @Preethii-R, sorry for the late reply. I was busy due to my health condition. Actually, your pull request is on the previous version of the website, which was in HTML and CSS. We have now successfully converted our code to Next.js and Tailwind CSS for back-end integration and payment gateway. So please don't be discouraged; I'm closing this pull request. You can work on any new issue, and I'll be happy to assign it to you. Make sure to join our [Discord server](https://discord.gg/Rg8T5gtE) for the latest announcements regarding the website and features as well. _Thank you!_

**Pull request closed without merging**
