### PR TITLE
Make the both navbar Sticky

### PR DESCRIPTION
**Pull request by Suvadip-sana**
## Description

1)   I make the navbar sticky for both mobile and desktop. I make the both navbar sticky, seller nav & also customer nav as per the  ISSUE #730 

2) I fix the mobile navbar problem for cart page, where the mobile dropdown menubar background is transparent, So i increase the Z - index. As per the ISSUE #791 

<br/>

## Related Issues

- Closes #

**Fix two ISSUE**
One is #730 
Second is #791 

<br/>

## Screenshots / videos (if applicable)

Solved first ISSUE  #730 

https://github.com/user-attachments/assets/9b718923-0e71-4d8a-925e-51e0eb138185

<br/>

Solved second ISSUE  #791 

https://github.com/user-attachments/assets/6d687d68-29fa-47f9-b531-5479aac4e3df

@mdazfar2   Please check it out and Don't forget to add all labels for `two ISSUE`

One is for #730  another one for #791 that is `label-2` & `label-2`  and also rest other label under gssoc & hacktoberfest please.

**Thank You**

### CODE REVIEW

**Comment by Suvadip-sana** [comment]
@mdazfar2 
Please have a look.

**Comment by Suvadip-sana** [comment]
@mdazfar2 

You gave me `lavel-2`, `label-2` for each of the ISSUE, But here you gave me `label-3`  only😓 which degrade the 10 point.

okay that's good.😊

**Comment by mdazfar2** [comment]
Hey @Suvadip-sana, please don't be sad. I gave you `level 3`, which counts as very big points on the GSSoC leaderboard. Did you know about that? A `level 3` Pull Request merge means you increased your points by +45.

**Comment by Suvadip-sana** [comment]
@mdazfar2 Yes I just realise that.

Thank you for this.

**Pull request merged**
