### PR TITLE
[FIX] Contact Us Page Alignment Fixed

### LINKED ISSUE #257: [BUG] Contact Us Align Issue
## Alignment issue

- Address, Email, Phone and opening hours texts are not aligned with icons.

### Screenshots

image

### Any additional information?

_No response_

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by 4F24L**
## Contact Us Page Alignment Fixed
- Fixes #257 

### Before : 
image

### After ✅ :
image

### Please add hactoberfest and GSSoC24 label.

### CODE REVIEW

**Comment by mdazfar2** [comment]
Hey @4F24L, your changes don't reflect on my deployment server.

**Comment by 4F24L** [comment]
Why ?! What could be the issue ?

**Comment by 4F24L** [comment]
You can check by merging !! I don't know why it's happening.

**Comment by mdazfar2** [comment]
@4F24L checkout this video below:



https://github.com/user-attachments/assets/02324d48-e405-421f-b6cd-db23a778c915

**Comment by mdazfar2** [comment]
sorry @4F24L I cannot reopened this PR because you deleted your branch

**Comment by 4F24L** [comment]
That was by mistake; restored the branch.

**Comment by 4F24L** [comment]
Should I make a new branch??

**Comment by mdazfar2** [comment]
> Should I make a new branch??

sure, and create new PR

**Pull request closed without merging**
