### PR TITLE
Improved form accessibility

### PR DESCRIPTION
**Pull request by shreyad2806**
#26 
Improving form accessibility involves ensuring that users with disabilities can easily interact with and understand your form.

<div class="form-group">
  <input type="text" id="name" placeholder="Name">
</div>

<div class="form-group">
  <label for="name">Name:</label>
  <input type="text" id="name" aria-label="Enter your name" aria-required="true" placeholder="Name">
</div>

<div class="form-group">
  <input type="email" id="email" placeholder="Email">
</div>

<div class="form-group">
  <label for="email">Email:</label>
  <input type="email" id="email" aria-label="Enter your email" aria-required="true" placeholder="Email">
</div>

<div class="form-group">
  <textarea id="message" placeholder="Message"></textarea>
</div>

<div class="form-group">
  <label for="message">Message:</label>
  <textarea id="message" aria-label="Enter your message" aria-required="true" placeholder="Message"></textarea>
</div>

added in css
/* Add focus state styles */
.form-group input:focus,
.form-group textarea:focus {
  border-color: #337ab7; /* High contrast color */
  box-shadow: 0 0 10px rgba(51, 122, 183, 0.5);
}

### CODE REVIEW

**Comment by shreyad2806** [comment]
Is my pull request proper or do I have to modify someting

**Comment by shreyad2806** [comment]
Heyy Is something wrong with the pull request?

**Comment by Kavita1928** [comment]
@shreyad2806 your branch is having conflict please resolve it

**Comment by shreyad2806** [comment]
Resolved the conflicts

**Pull request closed without merging**
