### PR TITLE
Adding Confetti Effect on Contributors Page

### LINKED ISSUE #1054: [Feat] Adding Confetti Animation on the Contributors Page
### Description

We can enhance the user experience on the contributors page by adding a confetti effect that triggers when the page loads. This feature will celebrate the contributions of our users and create a more engaging atmosphere.

#### Demo 
Screenshot 2024-11-03 at 2 20 30 AM

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by IkkiOcean**
**Description**  
This PR introduces a confetti effect on the `ContributorsPage` that activates when contributor data is successfully fetched. The confetti runs briefly for 6 seconds, creating a celebratory moment when users view the list of contributors.

**Implementation Details**  
1. **State Management**  
   - A state variable manages when the confetti is displayed and automatically toggles off after 6 seconds using a timeout.
  
2. **Responsive Window Handling**  
   - Confetti dimensions are adjusted based on window size, ensuring it remains responsive during window resize events.

3. **Confetti Component Integration**  
   - The confetti effect is integrated using a React component, dynamically adjusting its visibility based on the component's loading state.

---

**Screenshot**  

- Desktop 

https://github.com/user-attachments/assets/d77ce40c-a9ae-434d-8544-08d95d49233b

- Mobile

https://github.com/user-attachments/assets/705274e8-b5fa-4f97-8ec7-d072d71b491e

---

### Checklist  
- [x] Confetti effect added
- [x] Effect stops after 6 seconds
- [x] Responsive dimensions on window resize
- [x] Code reviewed and tested

**Linked Issues**  
- Closes #1054

### CODE REVIEW

**Comment by mdazfar2** [comment]
Hey @IkkiOcean, this is really nice, but there's a problem. When we click on the GitHub Contributors button, it doesn’t automatically scroll up; we have to manually scroll, which feels a bit weird. Please correct this so that when a user clicks the GitHub Contributors button, the footer shows, allowing every contributor to be seen without manual scrolling. Hope you understand.

**Comment by IkkiOcean** [comment]
@mdazfar2 I'm sorry I didn't understand that. Right now when we click GitHub contributor on the footer it redirects to the page at the top position as default. What do you need correction in it?

**Comment by mdazfar2** [comment]
> @mdazfar2 I'm sorry I didn't understand that. Right now when we click GitHub contributor on the footer it redirects to the page at the top position as default. What do you need correction in it

That's amazing! Actually, I was wrong, actually it takes time to reload. No problem, it's fine.

**Review by mdazfar2 — APPROVED** [review]
Amazing work @IkkiOcean 👏

**Comment by mdazfar2** [comment]
Hey @IkkiOcean, I noticed that I asked you to display only 4 contributor profiles in a row, but no changes were made for the desktop screen size at 100%. Could you please fix this in a new issue?

**Comment by IkkiOcean** [comment]
@mdazfar2 okay sure. I thought you agreed for cards per row depending on the screen size that's why I didnt touch it. I will raise the issue right away

**Pull request merged**
