### PR TITLE
Fixes the Logo Issues

### PR DESCRIPTION
**Pull request by rupeshv2121**
Issue Number #250 
I fix the logo issues and make changes which includes github logo and portfolio logo alongwith i active the the logo so that every logo work properly

### CODE REVIEW

**Comment by mdazfar2** [comment]
hey @rupeshv2121 again you not updated on team page 


{B1586B69-51C5-47F6-83F5-A3F7A78B841C}

**Comment by rupeshv2121** [comment]
ohh That is the problem

**Comment by rupeshv2121** [comment]
wait 5 mins sir Really sorry

**Comment by rupeshv2121** [comment]
image

Sir pls check

**Comment by rupeshv2121** [comment]
Sir pls tell me all my mistakes resolved

**Review by mdazfar2 — APPROVED** [review]
Amazing @rupeshv2121

**Pull request merged**
