### PR TITLE
Added responsive password strength meter 

### PR DESCRIPTION
**Pull request by PavanTeja2005**
## Description
Please merge this first, I had to submit the same PR two time because of conficts.
Fixed PR #401 #381 

<br/>

## Related Issues

Fixed Issue #340 

<br/>

### CODE REVIEW

**Comment by PavanTeja2005** [comment]
@Kavita1928 Please check this resolved conflicts

**Comment by PavanTeja2005** [comment]
@mdazfar2 Please check this.

**Comment by Kavita1928** [comment]
@PavanTeja2005 update your snc fork then create pr

**Comment by PavanTeja2005** [comment]
@Kavita1928 i have synchronised my repo now.
And,
I have experienced this two times already. I rise PR when I'm all in sync and then by the time you check already many others' might have already merged and then conflicts come.

**Comment by mdazfar2** [comment]
Hey @PavanTeja2005, sorry for the late reply. I was busy due to my health condition. Actually, your pull request is on the previous version of the website, which was in HTML and CSS. We have now successfully converted our code to Next.js and Tailwind CSS for back-end integration and payment gateway. So please don't be discouraged; I'm closing this pull request. You can work on any new issue, and I'll be happy to assign it to you. Make sure to join our [Discord server](https://discord.gg/Rg8T5gtE) for the latest announcements regarding the website and features as well. _Thank you!_

**Pull request closed without merging**
