### PR TITLE
Issue:- #580 Solved :- Added pop up Funcitonality

### LINKED ISSUE #580: [Feat] Adding a signin/Registration Popup on Home Page.
### Description

I want to add signin/registration pop on landing page of website, let me show you the design how it will look :- IN screenshots

This will be really a win to win deal as it will show some discount or trending offer to our customer and we will get a sign in to our website.

### Screenshots

This is the design I've created for your website and it's suitable :- 
image

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by PrAyAg9**
#580 Issue Solved:- 

## Description

I've done it as resolving previous pull request was not possible so i created one 

<br/>

## Related Issues

- Closes #580 

<br/>

## Screenshots / videos (if applicable)

image

### CODE REVIEW

**Comment by PrAyAg9** [comment]
@mdazfar2  Please check it out, I've raised new pull request as resolving previous was not possible. Check it out.

**Review by mdazfar2 — APPROVED** [review]

**Comment by mdazfar2** [comment]
Awesome work @PrAyAg9

**Comment by PrAyAg9** [comment]
@mdazfar2  Thanks a lot buddy and sorry for not following contribution rules but i did it to fasten the work process and to resolve my issue but i promise from next time i will send pr only if it's assigned.

**Comment by mdazfar2** [comment]
Best of luck @PrAyAg9

**Pull request merged**
