### PR TITLE
submit-page added

### PR DESCRIPTION
**Pull request by Shan-N**
Added a submit page

### CODE REVIEW

**Comment by mdazfar2** [comment]
@Shan-N mention the issue using a hashtag (#) so we can understand which issue your PR is referencing, and label your PR accordingly. Thank you!

- and also update the sync fork.

**Comment by Shan-N** [comment]
Issue #235

**Comment by mdazfar2** [comment]
@Shan-N share demo video of changes that's I can merge accordingly.

**Comment by Shan-N** [comment]
https://github.com/user-attachments/assets/2e9f1f9b-6fb2-4d60-b652-fe30d632a77c

here's a demo

**Comment by mdazfar2** [comment]
@Shan-N @Shan-N Instead of clicking "Return to Home," can it automatically return to the home page 2 to 3 seconds after submitting?

**Comment by Shan-N** [comment]
@mdazfar2 Done!!! Please accept the PR

**Pull request closed without merging**
