### PR TITLE
#198  Added hover effect to cards issue 

### PR DESCRIPTION
**Pull request by ratna-jaiswal**
I have added the hover effect to the cards of articles, blogs and product categories.

### CODE REVIEW

**Comment by ratna-jaiswal** [comment]
@mdazfar2 @Kavita1928

**Comment by mdazfar2** [comment]
@ratna-jaiswal mention the issue using a hashtag (#) so we can understand which issue your PR is referencing, and label your PR accordingly. Thank you!

- share recording of your changes

- and also update the sync fork.

**Comment by ratna-jaiswal** [comment]
#198 

https://github.com/user-attachments/assets/eb5ba37e-8e55-4b12-80ce-2b8df9e231a0

**Review by mdazfar2 — APPROVED** [review]
Thank you @ratna-jaiswal

**Pull request merged**
