### PR TITLE
Render categories page and add link to home page from logo.

### PR DESCRIPTION
**Pull request by muhafiz5814**
Fixes: #24 

Fixed the file name case in anchor tag link, causing not to render the categories page in production but able to render in local environment.
Also added link to home page from the website logo which was unresponsive earlier.

### CODE REVIEW

**Comment by mdazfar2** [comment]
@muhafiz5814 update sync fork once and let me know and remember that it will work from all the pages.

**Comment by muhafiz5814** [comment]
> @muhafiz5814 update sync fork once and let me know and remember that it will work from all the pages.

@mdazfar2 updated the fork and checked with all the pages.
Both the categories and logo links are working fine.

**Comment by mdazfar2** [comment]
@muhafiz5814, I merged someone's PR a minute ago. Please check your branch again and ping me.

**Review by mdazfar2 — APPROVED** [review]

**Comment by muhafiz5814** [comment]
hey @mdazfar2,
I think the label to be considered as gssoc extended contributor is `gssoc-ext` instead of `gssoc-extd`
Here is the [reference](https://discord.com/channels/1231112132595028008/1290984188635512863/1291000317881614347)

Can you please update the label on my PR so that it will be considered for gssoc.
Thank you.

**Comment by mdazfar2** [comment]
Okay! @muhafiz5814 I'll update it right now

**Comment by muhafiz5814** [comment]
Thanks @mdazfar2 👍

**Pull request merged**
