### PR TITLE
Added features like myorder, Cart , Wishlist

### PR DESCRIPTION
**Pull request by prvn-kumar01**
Added features like Myorder , Cart , Wishlist and alert message while click on these without login.

Uploading Easy.mp4…

### CODE REVIEW

**Comment by prvn-kumar01** [comment]
@mdazfar2 
Is it in working codition??

**Comment by mdazfar2** [comment]
No @prvn-kumar01 It is not working condition

**Review by mdazfar2 — APPROVED** [review]

**Comment by mdazfar2** [comment]
@prvn-kumar01 will remove your changes only for alert message

https://github.com/user-attachments/assets/e4cb7735-df75-44d4-8142-f535a03251b8

**Comment by prvn-kumar01** [comment]
What can I do now?

**Pull request merged**
