### PR TITLE
done

### PR DESCRIPTION
**Pull request by S7viks**
I fixed the bug, please check. 
issue number: #19
image

### CODE REVIEW

**Comment by mdazfar2** [comment]
@S7viks please update sync fork and let me know

**Comment by S7viks** [comment]
Please check, I've synced it.

**Comment by S7viks** [comment]
Please add labels, gssoc-extd and level

**Comment by S7viks** [comment]
@mdazfar2 please add labels to this issue, gssoc extd and level label

**Comment by mdazfar2** [comment]
@S7viks ohw.. thanks for letting me know.

**Pull request merged**
