### PR TITLE
Changed Icons in footer section

### PR DESCRIPTION
**Pull request by Bhanuprakash842**
Issue : #158 
Updated all the icons as per your instructions. Hope that you will merge my pr under gssoc-ext , hacktoberfest .
Screenshot 2024-10-05 191405

### CODE REVIEW

**Comment by mdazfar2** [comment]
Hello @Bhanuprakash842 update the sync fork and let me know.

**Comment by Bhanuprakash842** [comment]
> Hello @Bhanuprakash842 update the sync fork and let me know.

I have updated the sync fork..

**Comment by mdazfar2** [comment]
It is not updated @Bhanuprakash842 kindly update the sync fork 🍴

**Comment by mdazfar2** [comment]
Hello @Bhanuprakash842, there are a total of 19 pages on this website, and you added icons only to one page's footer, which is not ideal. I have to close this PR for now. Sorry, please don't be discouraged.

**Pull request closed without merging**
