### PR TITLE
Fixed inconsistent input fields border radius

### LINKED ISSUE #189: [BUG] Fix inconsistent border-radius for input fields across all forms
### Description

There is a styling issue where the input fields across various forms on the website have a border-radius applied only to the top-left and bottom-left corners. This creates an uneven and inconsistent appearance in the form fields. There seems to be clash in the styling for form input fields and search input field.

**Expected Behavior:** All corners (top-left, top-right, bottom-left, and bottom-right) of the form input fields should have the same border-radius for a balanced and consistent appearance.

Please assign this issue to me, I would like to work on this.

### Screenshots

image
image

### Any additional information?

_No response_

### What browser are you seeing the problem on?

_No response_

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by kavya410004**
This PR addresses the inconsistent border-radius styling in input fields across multiple forms on the site due to the clash in the styles of these form input fields and search input fields. 
**Changes:**
I have moved the style properties specific for search input field to separate classes to resolve this inconsistent border radius for the input fields.
**Result:**
The input fields across all forms are consistent.
The search bar appearance is same as before without any change.
**Screenshots:**
Before:
Screenshot 2024-10-05 165713
Screenshot 2024-10-05 165731

After:
image
image

The search bar appearance:

image

**Related Issue:**
Closes #189

Please review the code and let me know if any changes are needed.

### CODE REVIEW

**Comment by mdazfar2** [comment]
@kavya410004 kindly update sync fork and let me know.

**Comment by mdazfar2** [comment]
@kavya410004, update your forked branch so that I can merge your pull request.

**Comment by kavya410004** [comment]
@mdazfar2 I have updated my forked branch, Can you review it?

**Comment by mdazfar2** [comment]
@kavya410004 you didn't update the branch you created named "fix/input-border-radius." Kindly switch to that branch from your GitHub fork repo and then update the branch. I think you updated your `main` branch. Please update the branch from which you created the PR, `input-border-radius.`

**Comment by mdazfar2** [comment]
@kavya410004 Update this one;

{883BDFAB-5879-49D2-A38E-4C992075983F}

**Comment by kavya410004** [comment]
@mdazfar2 Thank you for showing it, I have updated the branch fix/input-border-radius#189

**Review by mdazfar2 — APPROVED** [review]
Alright! Thank you.

**Pull request merged**
