### PR TITLE
bug in Fashion page

### LINKED ISSUE #228: [BUG] Found a bug in Fashion page
### Description

On the Fashion page, clicking the Add to Cart button for products with titles that contain single quotes (e.g., "Men's Casual Shirt") does not trigger the alert message due to a JavaScript error caused by the single quote in the title.

### Steps to Reproduce

Go to the Fashion category page.
Click the Add to Cart button for one of the first three items, such as "Men's Casual Shirt".
Observe that the alert message does not appear as expected.

### Expected Behavior

When clicking the Add to Cart button for products with single quotes in their title, the alert should display correctly, showing the product name in the message.

### Screenshots

https://github.com/user-attachments/assets/2dda6c9e-b4e3-4a38-b3eb-12c998034847

### Any additional information?

Possible Solution
To handle the case where product_title contains special characters like single quotes, the onclick function should work properly without breaking due to the embedded quotes. A suggested fix involves escaping single quotes in the product title.
product.product_title.replace(/'/g, "\\'") replaces all single quotes (') in the product title with an escaped version (\'), so that the title won't break the JavaScript code when passed to addToCart().

### What browser are you seeing the problem on?

_No response_

### Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I have checked the existing issues
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by Prudhvi-232**
fixes #228 
fixed a bug in fashion page

https://github.com/user-attachments/assets/b3f1a70a-8f2e-41b2-af41-3c4b735eff56

### CODE REVIEW

**Comment by mdazfar2** [comment]
hello @Prudhvi-232 here I will send you the demo video of the alert message, how it appears and removes itself automatically in about 2-3 seconds:

https://github.com/user-attachments/assets/0c459506-21dc-4dd1-ab87-c7ab674f1779

**Comment by Prudhvi-232** [comment]
Hi @mdazfar2 

Thanks for the clarification! I understand you’re looking for the alert to disappear automatically after 2-3 seconds. I’m happy to implement that as well.

For now, I’d like to close this PR, as the original issue I fixed—where the alert message is not showing for product names with single quotes (like "Men's Casual Shirt") due to a JavaScript error. I handled this by escaping the quotes, and the alert should be working fine now. The work for this issue has been completed and is ready to merge.

Since the number of merged PRs is important for my contribution, I’m interested in creating a new issue and a separate PR for the 2-3 second auto-dismiss feature. That way, both fixes can be tracked individually.

Let me know if you’re okay with this approach, or if you'd prefer that I make the changes within the same issue.
Looking forward to your decision!

Thanks again for your feedback!

**Comment by mdazfar2** [comment]
@Prudhvi-232 Alright! Update sync fork 🍴 and let me know

**Comment by Prudhvi-232** [comment]
@mdazfar2, I've synced my fork with the latest changes. Let me know if everything looks good, or if there's anything else you'd like me to address!

**Comment by mdazfar2** [comment]
hey kindly update sync fork again and let me know

**Comment by Prudhvi-232** [comment]
I have just synced my fork with the latest changes from the upstream repository and resolved any conflicts. My branch is now up to date. Please let me know if there are any further changes or adjustments you'd like me to make.

**Review by mdazfar2 — APPROVED** [review]
Awesome work @Prudhvi-232

**Pull request merged**
