### PR TITLE
centered founder logo in about and teams

### PR DESCRIPTION
**Pull request by TanishqMehrunkarIIPSDAVV**
Centered founder logo in about and teams as per i gave the issue
please feel free to review it and contact me!!!
image

### CODE REVIEW

**Comment by thakuratul2** [comment]
@TanishqMehrunkarIIPSDAVV your branch having conflicts please fix it asap

**Comment by TanishqMehrunkarIIPSDAVV** [comment]
@thakuratul2 fixed and centered the logo at home page too

**Comment by thakuratul2** [comment]
@TanishqMehrunkarIIPSDAVV merged

**Comment by TanishqMehrunkarIIPSDAVV** [comment]
thanks 👍

**Pull request merged**
