### PR TITLE
added favicon, added 'inde.html' in all the empty href tags 

### PR DESCRIPTION
**Pull request by Ayush215mb**
Now on clicking on the logo/ezyshop in the navbar, homepage will be opened from all the existing pages.

### CODE REVIEW

**Comment by mdazfar2** [comment]
@Ayush215mb mention issue

**Comment by Ayush215mb** [comment]
@mdazfar2 Previously on clicking the logo/Brand-name the website didn't changed to homepage, I have added that feature so that anyone wanting to go to homepage can directly click on the logo and will be redirected to the homepage of the website, this looks more professional than the navbar-option 'home' which you are using right now.
I have added the logo as the favicon which was missing previously, now it looks more professional.

**Comment by mdazfar2** [comment]
@Ayush215mb, i mean mention issue by the #issue 

Use a (#) hashtag for your issue.

**Comment by Ayush215mb** [comment]
Accept my PR request 😞

**Review by mdazfar2 — APPROVED** [review]

**Comment by mdazfar2** [comment]
@Ayush215mb kindly resolved the conflict and let me know.

**Comment by Ayush215mb** [comment]
sorry, I was at college. just give me 5 mins

**Comment by Ayush215mb** [comment]
done bro, sorry for the late.
I was at college that's why it took a little time

**Comment by Ayush215mb** [comment]
@mdazfar2 Please add the labels again.

**Review by mdazfar2 — APPROVED** [review]
Thank you @Ayush215mb

**Pull request merged**
