### PR TITLE
Added Logo

### PR DESCRIPTION
**Pull request by adityakr0660**
I have added ezyshop logo at the navigation bar and footer.

### CODE REVIEW

**Comment by mdazfar2** [comment]
Hey @adityakr0660, can you please give me access to the logo so I can edit the logo color according to the website myself?

**Comment by adityakr0660** [comment]
ok

**Comment by mdazfar2** [comment]
@adityakr0660 Please let me know how you can give me access.

**Comment by Kavita1928** [comment]
@adityakr0660 solve this conflict

**Comment by adityakr0660** [comment]
It is in psd file and u can easily edit.

**Comment by mdazfar2** [comment]
hey @adityakr0660 Please share me the logo on my [mail](mailto:azfaralam.ops@gmail.com)

**Comment by adityakr0660** [comment]
what can i do ??
This branch has conflicts that must be resolved ??

**Pull request closed without merging**
