### PR TITLE
feat: Add custom 404 page with improved design and redirection

### PR DESCRIPTION
**Pull request by RachitSahu26**
## Description

This pull request introduces a new custom 404 page to enhance user experience for cases when a user navigates to a non-existent route.

<br/>
Key Changes:
Created New 404 Page:

Added not-found.js under app/ to handle unmatched routes.
This page ensures the site responds gracefully with a friendly message and navigational options.
Reusable UI Component:

Added ItemNotFound.tsx under components/ui/.
This component contains:
Message: “Oops! The page you are looking for can’t be found.”
Buttons:
Go Back (navigates back to the previous page).
Learn About Ezyshop (redirects to an info page).
Visual Element:

Placed not-found.png in the public/ directory and displayed it in the right section of the 404 page.
Redirection Logic:

Implemented automatic redirection to the homepage after 2 seconds using the useEffect hook from React.
Tailwind CSS Styling:

Improved the design of the 404 page with Tailwind CSS for a better user interface and consistent branding.

fixed: #873
## Related Issues

- Closes #
Closes # (Add issue reference here if applicable)

<br/>

## Screenshots / videos (if applicable)

https://github.com/user-attachments/assets/e1c65589-0f98-43ab-940d-9d156b273de8

Screenshot (387)

### CODE REVIEW

**Comment by mdazfar2** [comment]
@RachitSahu26 That's amazing, but in our entire codebase, we don't use any JavaScript files. Can you please convert it to TypeScript?

**Comment by mdazfar2** [comment]
@RachitSahu26 Right now, there is a deployment error with your pull request. Please check the screenshot below as proof.

When I merged your PR, the changes didn't reflect on our deployed site. Did you check `npm run lint` while committing?

I hope you read our [contributing guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md).

**Comment by RachitSahu26** [comment]
okay i am trying to fix it @mdazfar2

**Comment by RachitSahu26** [comment]
Everything runs smoothly on my local environment, but it seems to encounter issues when deployed on Vercel.

Could you please take a look and advise on how to proceed? Your guidance would be greatly appreciated!

Thank you for your help! @mdazfar2

**Comment by mdazfar2** [comment]
@RachitSahu26, the deployment to Vercel was successful! However, I noticed a JavaScript file in your PR, which seems out of place. Could you please convert it to TypeScript? This would align better with our project's structure and best practices.

**Comment by RachitSahu26** [comment]
converted file not-found.js to not-found.tsx @mdazfar2

**Comment by mdazfar2** [comment]
@RachitSahu26 you’ve done a really good job, thanks for that. Please update the sync fork before I merge and let me know once it's done.

**Comment by RachitSahu26** [comment]
sure , i have done this @mdazfar2

**Comment by RachitSahu26** [comment]
Screenshot (396)

**Comment by mdazfar2** [comment]
@RachitSahu26, you updated your `main` branch and create the Pull Request from the `Update-404-page` branch. You must sync the fork of your `Update-404-page` branch.

First, change the branch from `main` to `Update-404-page` and then click on "Update sync fork." Please see the screenshot below for better understanding.

<br>





<br/>

- Hope this time you understand please let me know if you updated sync fork in your `Update-404-page` branch.

**Comment by RachitSahu26** [comment]
now check it i hope ,everything should be fine @mdazfar2

**Review by mdazfar2 — APPROVED** [review]

**Comment by RachitSahu26** [comment]
Thank You @mdazfar2 💖😃

**Pull request merged**
