### PR TITLE
Fix the category page in navbar, which was broken initially.

### PR DESCRIPTION
**Pull request by Suvadip-sana**
I fix he broken category page on Navbar  category option. I was broken initially because it link with `Category.html` instead of `category.html` this.

Please go through with this and merge it.

### CODE REVIEW

**Comment by Suvadip-sana** [comment]
Please merge it! Thank You.

**Comment by mdazfar2** [comment]
@Suvadip-sana kindly updates the sync fork and it should open from all the pages. ***thank you***.

**Comment by Suvadip-sana** [comment]
I did not understand! Could you please elaborate in details?

**Comment by Suvadip-sana** [comment]
Ok! Now check. I update the sync fork. Should i open another pull request? Or is i ok with his? Please help me regarding this. Because it's my first time in Opensource.

**Review by mdazfar2 — APPROVED** [review]
Thank you @Suvadip-sana

**Pull request merged**
