### PR TITLE
added Teams-page-responsiveness

### LINKED ISSUE #446: [BUG] The TeamsPage of the NEXTJS version of the website is not responsive on smaller screen sizes
### Description

I will add appropriate Tailwind classes and restructuring to make it responsive for small screen sizes.

Kindly assign me this issue! :)

### Screenshots

image

### Any additional information?

_No response_

### What browser are you seeing the problem on?

_No response_

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

### LINKED ISSUE #466: [Feat] I want to implement search functionality and Notifications feature to the website.
### Description

search functionality -Helps users quickly find products or content on the website.
Notifications-Sends timely updates to users, keeping them engaged and informed even when they’re not on the site.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by ShivanshPlays**
## Description

This PR enhances the user experience of the Teams by implementing responsive design adjustments. The goal is to ensure that the page displays correctly across a variety of devices and screen sizes, providing a seamless experience for all users.

please Review the responsiveness across different devices and provide feedback.

<br/>

## Related Issues

- Closes #446 

<br/>

## Screenshots / videos (if applicable)

https://github.com/user-attachments/assets/6f53d9d6-7fd6-4888-842e-bc215ef2becf

### CODE REVIEW

**Review by mdazfar2 — APPROVED** [review]

**Comment by AKSHITHA-CHILUKA** [comment]
@ShivanshPlays its not 466 its 446 Please change your issues number .

Core Team Member 
GSSOC-EXT 
Thank You

**Comment by AKSHITHA-CHILUKA** [comment]
https://github.com/mdazfar2/Ezyshop/issues/466 
as i can see your pr in this issue

**Comment by ShivanshPlays** [comment]
@AKSHITHA-CHILUKA  
image
Yes, I added 466 by mistake and I changed it immediately within 5 minutes, It is 446 now, If any issue still persists please do tell

**Comment by AKSHITHA-CHILUKA** [comment]
Thanks @ShivanshPlays

**Review by MastanSayyad — COMMENTED** [review]
Hi @mdazfar2 again responsivness for a single page with only CSS changes
Update it to `level 1`

image

**Pull request merged**
